/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    plans: Plan;
    subscriptions: Subscription;
    entitlements: Entitlement;
    'stripe-events': StripeEvent;
    'api-keys': ApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    entitlements: EntitlementsSelect<false> | EntitlementsSelect<true>;
    'stripe-events': StripeEventsSelect<false> | StripeEventsSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Account holders, staff, and service accounts. Members register through the public account page; only admins change roles or enable API keys.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Optional display name.
   */
  name?: string | null;
  /**
   * admin: full control · staff: read-only admin access · member: account page · service: API-key-only automation limited to one scope (see Service scope).
   */
  role: 'admin' | 'staff' | 'member' | 'service';
  /**
   * Required for service accounts; each automation gets its own account and key. payments_store: webhook ledger and entitlement records for the payments service. gateway_sync: key-record export for the gateway. A scope grants nothing else.
   */
  serviceScope?: ('payments_store' | 'gateway_sync') | null;
  /**
   * Pseudonymous Stripe customer id, linked by checkout or webhook. No card or address data is ever stored here.
   */
  stripeCustomerId?: string | null;
  /**
   * Internal staff notes. Never returned to the member.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Offer ids mapped to Stripe prices that live only here and in the Stripe Dashboard; prices are never published on the site. The account page sells active subscription-mode plans only: one-time payment plans grant no entitlement and are refused at checkout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  /**
   * Stable public id, e.g. growth_monthly. Must match payments/contracts/v1/offers.json when the same offer is sold through /billing.
   */
  offerId: string;
  label: string;
  /**
   * Shown on the account page. Never include a price.
   */
  description?: string | null;
  mode: 'subscription' | 'payment';
  /**
   * Stripe price id (price_…), unique across plans so a subscription's price resolves to exactly one plan. Must belong to the same test/live mode as STRIPE_SECRET_KEY.
   */
  stripePriceId: string;
  /**
   * Whole number of units per checkout line item (Stripe accepts integers only).
   */
  quantity: number;
  /**
   * Only active plans are offered on the account page.
   */
  active?: boolean | null;
  /**
   * Managed API key policy granted to subscribers of this plan (see gateway/contracts/v1/key-record.schema.json).
   */
  gateway: {
    permissions?: ('manifest' | 'records' | 'resolver')[] | null;
    /**
     * Tokens per second (0 < rate <= 1000).
     */
    quotaRate: number;
    /**
     * Integer bucket capacity (1..10000, and at most rate × 86400).
     */
    quotaBurst: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Mirror of Stripe subscriptions, written only by verified webhooks (CMS) or the payments service store. Holds pseudonymous ids and enum statuses; no amounts, names, addresses, or card data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  stripeSubscriptionId: string;
  stripeCustomerId?: string | null;
  /**
   * Linked from checkout client_reference_id, subscription metadata, or the customer id on the user.
   */
  user?: (number | null) | User;
  plan?: (number | null) | Plan;
  /**
   * Billed Stripe price from the newest subscription event. The plan follows this price alone; a price no plan is configured for leaves the subscription without a plan, and offer metadata never restores one.
   */
  stripePriceId?: string | null;
  offer?: string | null;
  status:
    | 'incomplete'
    | 'incomplete_expired'
    | 'trialing'
    | 'active'
    | 'past_due'
    | 'canceled'
    | 'unpaid'
    | 'paused'
    | 'pending_subscription_event'
    | 'unknown';
  cancelAtPeriodEnd?: boolean | null;
  currentPeriodEnd?: string | null;
  livemode?: boolean | null;
  checkoutSessionId?: string | null;
  lastInvoiceId?: string | null;
  lastInvoiceStatus?: ('paid' | 'payment_failed') | null;
  /**
   * Unix seconds of the newest Stripe event applied from any family.
   */
  lastEventCreated?: number | null;
  /**
   * Watermark for checkout.session.* events; an older checkout event never overwrites a newer one.
   */
  lastCheckoutEventCreated?: number | null;
  /**
   * Watermark for customer.subscription.* events (status, cancellation, period).
   */
  lastSubscriptionEventCreated?: number | null;
  /**
   * Watermark for invoice.* events (last invoice status).
   */
  lastInvoiceEventCreated?: number | null;
  lastEventId?: string | null;
  source: 'cms' | 'payments';
  updatedAt: string;
  createdAt: string;
}
/**
 * Payments-service store records (Stripe ids and enum statuses only). Subscription-kind records are mirrored into Subscriptions automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements".
 */
export interface Entitlement {
  id: number;
  key: string;
  kind: 'checkout_session' | 'subscription' | 'unknown';
  offer?: string | null;
  offerKnown?: boolean | null;
  status: string;
  customer?: string | null;
  subscription?: string | null;
  checkoutSession?: string | null;
  paymentIntent?: string | null;
  livemode?: boolean | null;
  updatedAtEpoch?: number | null;
  sourceEvent?: string | null;
  source: string;
  /**
   * Record as written by the payments service store contract, plus the `revision` this collection stamps on every write.
   */
  record:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Webhook idempotency ledger shared by the CMS webhook and the payments service. Claims are unique per consumer and event (claimKey = source:eventId), so each consumer processes every event exactly once across replicas and neither can mark an event done for the other; the ledger stores ids and types only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-events".
 */
export interface StripeEvent {
  id: number;
  eventId: string;
  source: 'payments' | 'cms';
  /**
   * Derived as source:eventId; the unique index makes the first writer per consumer win.
   */
  claimKey: string;
  type?: string | null;
  livemode?: boolean | null;
  outcome?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Managed API key records issued to subscribers. Raw keys are never stored; revoking here takes effect at the next gateway key sync.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: number;
  keyId: string;
  /**
   * base64url HMAC-SHA-256 of the raw key; never the key itself.
   */
  verifier: string;
  user: number | User;
  /**
   * account: minted from /account and bound to the subscription below; if that subscription disappears the key is exported revoked. admin: created here without a granting subscription; follows the account's entitlement in its billing mode.
   */
  issuedBy: 'account' | 'admin';
  /**
   * Subscription that granted this key. The gateway export follows it: the key is exported revoked while that subscription is not active, and its permissions and quota follow the plan currently attached to it.
   */
  subscription?: (number | null) | Subscription;
  label?: string | null;
  state: 'active' | 'revoked' | 'expired';
  /**
   * Billing mode of the subscription that entitled this key. Test-mode keys are exported to the gateway only while the CMS itself runs with a Stripe test key, so they stop working at live promotion.
   */
  livemode: boolean;
  notBefore?: string | null;
  expiresAt?: string | null;
  revokedAt?: string | null;
  permissions: ('manifest' | 'records' | 'resolver')[];
  quotaRate: number;
  quotaBurst: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'entitlements';
        value: number | Entitlement;
      } | null)
    | ({
        relationTo: 'stripe-events';
        value: number | StripeEvent;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: number | ApiKey;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  serviceScope?: T;
  stripeCustomerId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  offerId?: T;
  label?: T;
  description?: T;
  mode?: T;
  stripePriceId?: T;
  quantity?: T;
  active?: T;
  gateway?:
    | T
    | {
        permissions?: T;
        quotaRate?: T;
        quotaBurst?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  stripeSubscriptionId?: T;
  stripeCustomerId?: T;
  user?: T;
  plan?: T;
  stripePriceId?: T;
  offer?: T;
  status?: T;
  cancelAtPeriodEnd?: T;
  currentPeriodEnd?: T;
  livemode?: T;
  checkoutSessionId?: T;
  lastInvoiceId?: T;
  lastInvoiceStatus?: T;
  lastEventCreated?: T;
  lastCheckoutEventCreated?: T;
  lastSubscriptionEventCreated?: T;
  lastInvoiceEventCreated?: T;
  lastEventId?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements_select".
 */
export interface EntitlementsSelect<T extends boolean = true> {
  key?: T;
  kind?: T;
  offer?: T;
  offerKnown?: T;
  status?: T;
  customer?: T;
  subscription?: T;
  checkoutSession?: T;
  paymentIntent?: T;
  livemode?: T;
  updatedAtEpoch?: T;
  sourceEvent?: T;
  source?: T;
  record?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe-events_select".
 */
export interface StripeEventsSelect<T extends boolean = true> {
  eventId?: T;
  source?: T;
  claimKey?: T;
  type?: T;
  livemode?: T;
  outcome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  keyId?: T;
  verifier?: T;
  user?: T;
  issuedBy?: T;
  subscription?: T;
  label?: T;
  state?: T;
  livemode?: T;
  notBefore?: T;
  expiresAt?: T;
  revokedAt?: T;
  permissions?: T;
  quotaRate?: T;
  quotaBurst?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}