import test from 'node:test';import assert from 'node:assert/strict';import {cpSync,existsSync,mkdirSync,mkdtempSync,readFileSync,renameSync,rmSync,symlinkSync,unlinkSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {dirname,resolve} from 'node:path';import {DERIVATION_FILES,FILES,generateEvidenceBackedCoverageContracts,verifyEvidenceBackedCoverageContractDrift} from '../../web/scripts/generate-evidence-backed-coverage-contracts.mjs';
const repo=resolve(import.meta.dirname,'../..'),source=resolve(repo,'evidence-backed-coverage/contracts/v1');function deps(root){for(const n of DERIVATION_FILES){mkdirSync(dirname(resolve(root,n)),{recursive:true});cpSync(resolve(repo,n),resolve(root,n))}}function fixture(fn){const root=mkdtempSync(resolve(tmpdir(),'ebc-'));try{cpSync(source,resolve(root,'source'),{recursive:true});mkdirSync(resolve(root,'public'));deps(root);fn(root)}finally{rmSync(root,{recursive:true,force:true})}}
test('publishes exact manifest atomically',()=>fixture(root=>{generateEvidenceBackedCoverageContracts(resolve(root,'source'),resolve(root,'public/v1'),root,{dependencyRoot:root});for(const n of FILES)assert.deepEqual(readFileSync(resolve(root,'public/v1',n)),readFileSync(resolve(root,'source',n)))}));
test('fails closed on dependency mutation before publication',()=>fixture(root=>{const target=resolve(root,DERIVATION_FILES[0]);assert.throws(()=>generateEvidenceBackedCoverageContracts(resolve(root,'source'),resolve(root,'public/v1'),root,{dependencyRoot:root,beforePublish(){writeFileSync(target,Buffer.concat([readFileSync(target),Buffer.from(' ')]))}}),/changed/);assert.equal(existsSync(resolve(root,'public/v1')),false)}));
test('fails closed when a staged file is rewritten in place',()=>fixture(root=>{assert.throws(()=>generateEvidenceBackedCoverageContracts(resolve(root,'source'),resolve(root,'public/v1'),root,{dependencyRoot:root,beforePublish({stage}){writeFileSync(resolve(stage,FILES[0]),'changed')}}),/changed/);assert.equal(existsSync(resolve(root,'public/v1')),false)}));
test('fails closed when a staged file is replaced',()=>fixture(root=>{assert.throws(()=>generateEvidenceBackedCoverageContracts(resolve(root,'source'),resolve(root,'public/v1'),root,{dependencyRoot:root,beforePublish({stage}){rmSync(resolve(stage,FILES[0]));writeFileSync(resolve(stage,FILES[0]),readFileSync(resolve(source,FILES[0])))}}),/changed/);assert.equal(existsSync(resolve(root,'public/v1')),false)}));
test('fails closed when output parent is swapped',()=>fixture(root=>{const parent=resolve(root,'public'),old=resolve(root,'public-old');assert.throws(()=>generateEvidenceBackedCoverageContracts(resolve(root,'source'),resolve(parent,'v1'),root,{dependencyRoot:root,beforePublish(){renameSync(parent,old);mkdirSync(parent)}}),/parent replaced|changed/);assert.equal(existsSync(resolve(parent,'v1')),false);assert.equal(existsSync(resolve(old,'v1')),false)}));
test('exclusive publication lock rejects a concurrent writer',()=>fixture(root=>{const lock=resolve(root,'public/.evidence-backed-coverage.lock');writeFileSync(lock,'other writer');assert.throws(()=>generateEvidenceBackedCoverageContracts(resolve(root,'source'),resolve(root,'public/v1'),root,{dependencyRoot:root}),/EEXIST/);assert.equal(readFileSync(lock,'utf8'),'other writer');assert.equal(existsSync(resolve(root,'public/v1')),false)}));
test('inode-pinned lock replacement fails before final rename',()=>fixture(root=>{assert.throws(()=>generateEvidenceBackedCoverageContracts(resolve(root,'source'),resolve(root,'public/v1'),root,{dependencyRoot:root,beforeRename({lock}){unlinkSync(lock);writeFileSync(lock,'replacement')}}),/publication lock replaced/);assert.equal(existsSync(resolve(root,'public/v1')),false);assert.equal(readFileSync(resolve(root,'public/.evidence-backed-coverage.lock'),'utf8'),'replacement')}));
test('rejects source and output-parent symlinks',()=>{const root=mkdtempSync(resolve(tmpdir(),'ebc-'));try{mkdirSync(resolve(root,'real'));mkdirSync(resolve(root,'public'));deps(root);symlinkSync(source,resolve(root,'source'));assert.throws(()=>generateEvidenceBackedCoverageContracts(resolve(root,'source'),resolve(root,'public/v1'),root,{dependencyRoot:root}),/symlink/);rmSync(resolve(root,'public'),{recursive:true});symlinkSync(resolve(root,'real'),resolve(root,'public'));assert.throws(()=>generateEvidenceBackedCoverageContracts(source,resolve(root,'public/v1'),root,{dependencyRoot:root}),/symlink|unsafe/)}finally{rmSync(root,{recursive:true,force:true})}});
test('tracked source and public output verify without mutation',()=>assert.deepEqual(verifyEvidenceBackedCoverageContractDrift(),{published:false,reason:'exact_read_only_no_op'}));
