import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { descriptorFromReleaseBytes } from '../gateway/src/artifacts.mjs';
import { buildRecordsArtifact } from '../web/scripts/api-records-transform.mjs';

const SHA=/^sha256:[0-9a-f]{64}$/; const RID=/^weh_[0-9a-f]{24}$/; const SID=/^ebc_syn_[a-z0-9_]{6,40}$/; const IDENT=/^[a-z0-9][a-z0-9.-]*\.invalid$/; const DATE=/^20\d\d-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\d|3[01])$/;
export const DIMENSIONS=Object.freeze(['channels','documented_geography','documented_hours','documented_languages','field_evidence','recorded_verification_date']);
export const LIMITATIONS=Object.freeze([
  'Every terminal observation is independently derived from exact released-record field/value bytes; retained descriptions and review digests cannot override that derivation.',
  'Recorded evidence does not prove real-time availability, answering, eligibility, capacity, safety, outcomes, or universal geographic coverage.',
  'Field evidence and recorded verification date report bounded literal field/value presence only and make no trust, confirmation, freshness, or recency inference.',
  'This static synthetic assessment has no canonical-write, ranking, recommendation, comparison, intake, telemetry, outreach, commercial, pricing, billing, SLA, DPA, or security authority.',
  'Provider or claimant assertions are untrusted and cannot self-validate.'
]);
const STATES=Object.freeze(['observed','not_observed','unknown','not_assessed','partially_assessed','mixed']);
const OBSERVATIONS=Object.freeze({present:'observed',absent:'not_observed',indeterminate:'unknown',not_reviewed:'not_assessed'});
const plain=x=>x!==null&&typeof x==='object'&&!Array.isArray(x)&&Object.getPrototypeOf(x)===Object.prototype;
function exact(x,keys,label){assert.ok(plain(x),`${label} must be object`);assert.deepEqual(Object.keys(x).sort(),[...keys].sort(),`${label} has missing or prohibited fields`)}
export const pin=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
export const canonicalBytes=v=>Buffer.from(JSON.stringify(v));
function validDate(x){return typeof x==='string'&&DATE.test(x)&&new Date(`${x}T00:00:00Z`).toISOString().slice(0,10)===x}
function date(x){assert.ok(validDate(x),'invalid calendar date')}
function forbiddenText(x,path){const normalized=x.normalize('NFKC');assert.equal(normalized,x,`non-NFKC text at ${path}`);assert.doesNotMatch(normalized,/\p{Cf}|[\p{Cc}\p{Cs}]/u,`control or bidi text at ${path}`);const runs=normalized.match(/\p{Nd}[\p{Nd}(). /_\-]*\p{Nd}/gu)??[];assert.equal(runs.some(run=>(run.match(/\p{Nd}/gu)??[]).length>=7),false,`phone-like run at ${path}`);assert.doesNotMatch(normalized,/(?:[A-Za-z][A-Za-z0-9+.-]*\s*(?::|\[\.\])|\/\s*\/|@|\bat\b\s+[A-Za-z0-9]|(?:[A-Za-z0-9-]+\s*(?:\.|\[\.\]|\bdot\b)\s*)+[A-Za-z]{2,})/iu,`locator leaked at ${path}`)}
function leakage(x,path='$'){if(Array.isArray(x)){x.forEach((v,i)=>leakage(v,`${path}[${i}]`));return}if(plain(x)){for(const [k,v] of Object.entries(x))leakage(v,`${path}.${k}`);return}if(typeof x!=='string')return;if(SHA.test(x)||RID.test(x)||SID.test(x)||IDENT.test(x)||DATE.test(x)||/^\/(?!\/)[a-z0-9._/-]+$/.test(x)||DIMENSIONS.includes(x)||STATES.includes(x)||Object.keys(OBSERVATIONS).includes(x)||LIMITATIONS.includes(x)||['accepted','independent_reviewer','canonical_source','provider_assertion','static_synthetic_reference','reviewed_assertion','evidence-backed-coverage-source-evidence/v1','evidence-backed-coverage-review-decision/v1','evidence-backed-coverage-input/v1','evidence-backed-coverage-assessment/v1','CONSPICUOUSLY SYNTHETIC TEST EVIDENCE ONLY','CONSPICUOUSLY SYNTHETIC INDEPENDENT REVIEW ONLY'].includes(x))return;assert.ok(x.length<=240,`unbounded text at ${path}`);forbiddenText(x,path);assert.match(x,/^[A-Za-z0-9 _.,'()&/\-]+$/,`unsafe text at ${path}`)}
function parseArtifact(bytes,label){assert.ok(Buffer.isBuffer(bytes)&&bytes.length>0,`${label} bytes required`);let value;try{value=JSON.parse(bytes)}catch{throw Error(`invalid ${label} artifact JSON`)}leakage(value,`$.${label.replaceAll(' ','_')}`);return value}
function validateArtifactReference(ref,path,bytes,label){exact(ref,['path','sha256','bytes'],`${label} reference`);assert.equal(ref.path,path,`${label} path mismatch`);assert.equal(ref.sha256,pin(bytes),`${label} sha256 mismatch`);assert.equal(ref.bytes,bytes.length,`${label} byte count mismatch`)}
export function releasedLiteralObservation(recordId,dimension,record){if(!plain(record)||record.id!==recordId)return'not_reviewed';switch(dimension){case'channels':{const value=record.channels;if(!plain(value)||Object.keys(value).sort().join(',')!=='chat,phone,text'||Object.values(value).some(x=>typeof x!=='boolean'))return'not_reviewed';return Object.values(value).some(Boolean)?'present':'absent'}case'documented_geography':return typeof record.geography==='string'?(record.geography.length>0?'present':'absent'):'not_reviewed';case'documented_hours':return record.hours===null?'absent':typeof record.hours==='string'?(record.hours.length>0?'present':'absent'):'not_reviewed';case'documented_languages':return Array.isArray(record.languages)&&record.languages.every(x=>typeof x==='string'&&x.length>0)?(record.languages.length>0?'present':'absent'):'not_reviewed';case'field_evidence':return Array.isArray(record.sources)&&record.sources.every(x=>typeof x==='string'&&x.length>0)?(record.sources.length>0?'present':'absent'):'not_reviewed';case'recorded_verification_date':return record.last_verified===null?'absent':validDate(record.last_verified)?'present':'not_reviewed';default:return'not_reviewed'}}
export function validateRecordsArtifact(canonicalBytes,recordsBytes,datasetSha,recordIds){let canonical,records;try{canonical=JSON.parse(canonicalBytes);records=JSON.parse(recordsBytes)}catch{throw Error('invalid canonical or records JSON')}const expected=buildRecordsArtifact(canonical,datasetSha);exact(records,['api_version','dataset_version','records'],'records artifact');assert.deepEqual(records,expected,'complete released records artifact parity mismatch');assert.equal(Object.keys(records.records).length,Object.keys(expected.records).length);for(const id of recordIds)assert.ok(Object.hasOwn(records.records,id),'selected record absent from records artifact');return records.records}
function validateEvidenceRow(e,footprint,sources,records){exact(e,['evidence_id','record_id','dimension','source_kind','source_id','source_reference_sha256','observed_on','assertion_kind','state'],'evidence');assert.match(e.evidence_id,SID);assert.ok(footprint.includes(e.record_id));assert.ok(DIMENSIONS.includes(e.dimension));assert.equal(e.assertion_kind,'reviewed_assertion');assert.ok(['canonical_source','provider_assertion'].includes(e.source_kind));assert.match(e.source_id,SID);assert.match(e.source_reference_sha256,SHA);const source=sources.get(e.source_id);assert.ok(source,'unknown retained source');assert.equal(source.source_kind,e.source_kind,'source kind mismatch');assert.equal(e.source_reference_sha256,pin(canonicalBytes(source.retained_observation)),'source reference digest mismatch');const o=source.retained_observation;assert.equal(o.record_id,e.record_id,'retained observation record mismatch');assert.equal(o.dimension,e.dimension,'retained observation dimension mismatch');assert.equal(o.observed_on,e.observed_on,'retained observation date mismatch');date(e.observed_on);const released=records[e.record_id];assert.ok(released,'released record missing');assert.equal(released.id,e.record_id,'released record identity mismatch');const literal=releasedLiteralObservation(e.record_id,e.dimension,released);assert.equal(o.literal_observation,literal,`${e.dimension} retained observation contradicts released record bytes`);assert.equal(e.state,OBSERVATIONS[literal],`${e.dimension} state contradicts released record bytes`);if(e.source_kind==='provider_assertion')assert.notEqual(e.state,'observed','provider assertions cannot establish observed evidence')}
function validateReview(r,evidence,sourceBytes){exact(r,['review_id','reviewer_identity','claimant_identity','decision','reviewed_on','source_evidence_artifact','evidence_row_digests','conflict_of_interest'],'review');assert.match(r.review_id,SID);assert.match(r.reviewer_identity,IDENT);assert.match(r.claimant_identity,IDENT);assert.notEqual(r.reviewer_identity,r.claimant_identity,'reviewer self-review');assert.equal(r.conflict_of_interest,false);assert.equal(r.decision,'accepted','accepted independent review required');date(r.reviewed_on);validateArtifactReference(r.source_evidence_artifact,'/synthetic/source-evidence.json',sourceBytes,'review-bound source evidence');const expected=evidence.map(e=>({evidence_id:e.evidence_id,sha256:pin(canonicalBytes(e))})).sort((a,b)=>a.evidence_id.localeCompare(b.evidence_id));assert.deepEqual(r.evidence_row_digests,expected,'reviewed evidence row digests mismatch')}
function validateRelease(r,canonicalBytes,releaseBytes,indexBytes,recordsBytes){const descriptor=descriptorFromReleaseBytes(releaseBytes,indexBytes),release=JSON.parse(releaseBytes);exact(r,['release_id','release_sha256','artifact_index_sha256','records_artifact'],'release');assert.equal(r.release_id,descriptor.release_id);assert.equal(r.release_sha256,pin(releaseBytes));assert.equal(r.artifact_index_sha256,pin(indexBytes));const artifact=release.relationships['/api/v1/records.json'];assert.deepEqual(r.records_artifact,artifact);assert.equal(artifact.sha256,pin(recordsBytes));assert.equal(artifact.bytes,recordsBytes.length);assert.equal(descriptor.dataset_version,pin(canonicalBytes));return descriptor}

function boundArtifacts(v,sourceBytes,reviewBytes,records){validateArtifactReference(v.source_evidence_artifact,'/synthetic/source-evidence.json',sourceBytes,'source evidence');const artifact=parseArtifact(sourceBytes,'source evidence');exact(artifact,['schema','synthetic_notice','sources','evidence'],'source evidence artifact');assert.equal(artifact.schema,'evidence-backed-coverage-source-evidence/v1');assert.equal(artifact.synthetic_notice,'CONSPICUOUSLY SYNTHETIC TEST EVIDENCE ONLY');const sources=new Map();for(const source of artifact.sources){exact(source,['source_id','source_kind','retained_observation'],'retained source');assert.match(source.source_id,SID);assert.ok(['canonical_source','provider_assertion'].includes(source.source_kind));const o=source.retained_observation;exact(o,['record_id','dimension','literal_observation','observed_on'],'retained observation');assert.match(o.record_id,RID);assert.ok(DIMENSIONS.includes(o.dimension));assert.ok(Object.hasOwn(OBSERVATIONS,o.literal_observation));date(o.observed_on);assert.ok(!sources.has(source.source_id));sources.set(source.source_id,source)}const evidence=artifact.evidence;assert.ok(Array.isArray(evidence));const ids=new Set(),pairs=new Set();for(const e of evidence){validateEvidenceRow(e,v.footprint.record_ids,sources,records);assert.ok(!ids.has(e.evidence_id),'duplicate evidence ID');ids.add(e.evidence_id);const pair=`${e.record_id}\0${e.dimension}`;assert.ok(!pairs.has(pair),'duplicate record/dimension terminal state');pairs.add(pair)}for(const id of v.footprint.record_ids)for(const d of DIMENSIONS)assert.ok(pairs.has(`${id}\0${d}`),`missing record/dimension terminal state: ${id}/${d}`);assert.equal(evidence.length,v.footprint.record_count*DIMENSIONS.length);validateArtifactReference(v.review_decision_artifact,'/synthetic/review-decision.json',reviewBytes,'review decision');const reviewArtifact=parseArtifact(reviewBytes,'review decision');exact(reviewArtifact,['schema','synthetic_notice','review'],'review decision artifact');assert.equal(reviewArtifact.schema,'evidence-backed-coverage-review-decision/v1');assert.equal(reviewArtifact.synthetic_notice,'CONSPICUOUSLY SYNTHETIC INDEPENDENT REVIEW ONLY');validateReview(reviewArtifact.review,evidence,sourceBytes);return{evidence,review:reviewArtifact.review}}
export function validateInput(v,canonicalBytesValue,releaseBytes,indexBytes,recordsBytes,sourceBytes,reviewBytes){leakage(v);exact(v,['schema','assessment_id','dataset_sha256','release','footprint','source_evidence_artifact','required_review_decision','review_decision_artifact'],'input');assert.equal(v.schema,'evidence-backed-coverage-input/v1');assert.match(v.assessment_id,SID);assert.equal(v.required_review_decision,'accepted');assert.equal(v.dataset_sha256,pin(canonicalBytesValue));validateRelease(v.release,canonicalBytesValue,releaseBytes,indexBytes,recordsBytes);exact(v.footprint,['record_ids','record_count'],'footprint');assert.ok(Array.isArray(v.footprint.record_ids)&&v.footprint.record_ids.length>0);assert.deepEqual(v.footprint.record_ids,[...v.footprint.record_ids].sort());assert.equal(new Set(v.footprint.record_ids).size,v.footprint.record_ids.length);assert.equal(v.footprint.record_count,v.footprint.record_ids.length);v.footprint.record_ids.forEach(id=>assert.match(id,RID));const records=validateRecordsArtifact(canonicalBytesValue,recordsBytes,v.dataset_sha256,v.footprint.record_ids);const {evidence,review}=boundArtifacts(v,sourceBytes,reviewBytes,records);assert.ok(evidence.every(e=>e.observed_on<=review.reviewed_on),'source-date/evidence mismatch');return true}
export function coverageStateForCounts(c,n){assert.ok(Number.isSafeInteger(n)&&n>0,'positive footprint required');for(const k of ['numerator','denominator','unknown_count','not_observed_count','not_assessed_count'])assert.ok(Number.isSafeInteger(c[k])&&c[k]>=0,`${k} must be a nonnegative safe integer`);assert.equal(c.numerator+c.unknown_count+c.not_observed_count,c.denominator,'assessed-state partition mismatch');assert.equal(c.denominator+c.not_assessed_count,n,'footprint partition mismatch');if(c.denominator===0)return'not_assessed';if(c.not_assessed_count>0)return'partially_assessed';if(c.unknown_count>0)return'unknown';if(c.numerator===n)return'observed';if(c.not_observed_count===n)return'not_observed';return'mixed'}
export function deriveAssessment(v,...bytes){validateInput(v,...bytes);const records=JSON.parse(bytes[3]).records,{evidence,review}=boundArtifacts(v,bytes[4],bytes[5],records);const dimensions=DIMENSIONS.map(name=>{const rows=evidence.filter(e=>e.dimension===name),count=s=>rows.filter(e=>e.state===s).length,d={name,numerator:count('observed'),denominator:rows.filter(e=>e.state!=='not_assessed').length,unknown_count:count('unknown'),not_observed_count:count('not_observed'),not_assessed_count:count('not_assessed')};return{...d,coverage_state:coverageStateForCounts(d,v.footprint.record_count)}});return{schema:'evidence-backed-coverage-assessment/v1',kind:'static_synthetic_reference',assessment_id:v.assessment_id,dataset_sha256:v.dataset_sha256,release:structuredClone(v.release),footprint:structuredClone(v.footprint),review:structuredClone(review),dimensions,limitations:[...LIMITATIONS],effects:{canonical_mutation:false,ranking_or_search_effect:false,publication_authority:false,commercial_activation:false}}}
export function validateAssessment(a,input,...bytes){assert.ok(input,'accepted bound input and artifact bytes required');leakage(a);exact(a,['schema','kind','assessment_id','dataset_sha256','release','footprint','review','dimensions','limitations','effects'],'assessment');assert.equal(a.schema,'evidence-backed-coverage-assessment/v1');assert.equal(a.kind,'static_synthetic_reference');assert.deepEqual(a.dimensions.map(x=>x.name),DIMENSIONS);for(const d of a.dimensions){exact(d,['name','numerator','denominator','unknown_count','not_observed_count','not_assessed_count','coverage_state'],'dimension');assert.equal(d.coverage_state,coverageStateForCounts(d,a.footprint.record_count))}assert.deepEqual(a.limitations,LIMITATIONS);exact(a.effects,['canonical_mutation','ranking_or_search_effect','publication_authority','commercial_activation'],'effects');Object.values(a.effects).forEach(x=>assert.equal(x,false));validateInput(input,...bytes);assert.deepEqual(a,deriveAssessment(input,...bytes),'assessment does not match accepted bound inputs and artifact bytes');return true}
