// Seed D1 from hotlines.json (or information.json as fallback).
// Emits SQL on stdout so you can pipe it to wrangler:
//   node db/seed.mjs > db/seed.sql
//   wrangler d1 execute world-hotlines --file=./db/seed.sql
//
// This script does not talk to D1 directly — keeping it wrangler-driven means
// you can run it anywhere and also eyeball the SQL before applying.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
// Canonical dataset lives at the repo root, two levels up from web/db/.
const REPO_ROOT = resolve(__dirname, '..', '..');

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf-8'));
}

function sqlEscape(value) {
  if (value == null) return 'NULL';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  if (typeof value === 'boolean') return value ? '1' : '0';
  const s = String(value).replace(/'/g, "''");
  return `'${s}'`;
}

function jsonCol(arr) {
  return sqlEscape(JSON.stringify(arr ?? []));
}

function loadCanonical() {
  try {
    const hot = readJson(resolve(REPO_ROOT, 'hotlines.json'));
    if (hot && Array.isArray(hot.countries)) return { format: 'v2', data: hot.countries };
  } catch {}
  const legacy = readJson(resolve(REPO_ROOT, 'information.json'));
  return { format: 'legacy', data: legacy };
}

function normalizeLegacy(country) {
  return {
    country: country.country,
    'alpha-2': country['alpha-2'],
    'alpha-3': country['alpha-3'],
    region: null,
    subregion: null,
    general_emergency: [],
    notes: null,
    hotlines: (country.hotlines ?? []).map((h) => ({
      name: h.name,
      organization: h.name,
      category: /suicide|crisis/i.test(h.name) ? 'suicide_crisis' : 'general_support',
      voice_numbers: h.numbers ?? [],
      sms_numbers: [],
      text_numbers: [],
      short_codes: [],
      chat_url: null,
      email: null,
      website: null,
      hours: null,
      languages: [],
      cost: 'unknown',
      target: null,
      geography: country.country,
      notes: '',
      verification_status: 'legacy_unverified',
      last_verified: null,
      sources: ['information.json'],
    })),
  };
}

const { format, data } = loadCanonical();
const countries = format === 'v2' ? data : data.map(normalizeLegacy);

const lines = [];
lines.push('-- Generated by db/seed.mjs — do not hand-edit');
lines.push('BEGIN TRANSACTION;');
lines.push('DELETE FROM hotlines;');
lines.push('DELETE FROM countries;');

for (const c of countries) {
  lines.push(
    `INSERT INTO countries (alpha2, alpha3, name, region, subregion, general_emergency, notes) VALUES (` +
      [
        sqlEscape(c['alpha-2']),
        sqlEscape(c['alpha-3']),
        sqlEscape(c.country),
        sqlEscape(c.region ?? null),
        sqlEscape(c.subregion ?? null),
        jsonCol(c.general_emergency ?? []),
        sqlEscape(c.notes ?? null),
      ].join(', ') +
      ');'
  );
  for (const h of c.hotlines ?? []) {
    lines.push(
      `INSERT INTO hotlines (country_code, name, organization, category, voice_numbers, sms_numbers, text_numbers, short_codes, chat_url, email, website, hours, languages, cost, target, geography, notes, verification_status, last_verified, sources) VALUES (` +
        [
          sqlEscape(c['alpha-2']),
          sqlEscape(h.name ?? h.organization ?? 'Hotline'),
          sqlEscape(h.organization ?? null),
          sqlEscape(h.category ?? 'general_support'),
          jsonCol(h.voice_numbers ?? []),
          jsonCol(h.sms_numbers ?? []),
          jsonCol(h.text_numbers ?? []),
          jsonCol(h.short_codes ?? []),
          sqlEscape(h.chat_url ?? null),
          sqlEscape(h.email ?? null),
          sqlEscape(h.website ?? null),
          sqlEscape(h.hours ?? null),
          jsonCol(h.languages ?? []),
          sqlEscape(h.cost ?? 'unknown'),
          sqlEscape(h.target ?? null),
          sqlEscape(h.geography ?? null),
          sqlEscape(h.notes ?? null),
          sqlEscape(h.verification_status ?? 'legacy_unverified'),
          sqlEscape(h.last_verified ?? null),
          jsonCol(h.sources ?? []),
        ].join(', ') +
        ');'
    );
  }
}

lines.push('COMMIT;');
process.stdout.write(lines.join('\n') + '\n');
console.error(
  `# seeded ${countries.length} countries, ` +
    `${countries.reduce((n, c) => n + (c.hotlines?.length ?? 0), 0)} hotlines (format: ${format})`
);
