import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {mkdtempSync,mkdirSync,readFileSync,rmSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {resolve} from 'node:path';
import {PRESENTATION_MAX_TTL_SECONDS,analyzeCompliance,canonicalSafetyBytes,issuePresentation,sha256,signSyntheticEvidence,validateBinaryObservation,validateFetchObservation,validateOutwardObservation,validatePresentationObservation,validateRenderAttestation,verifyPresentation} from '../model.mjs';
import {assertInternalNonpublication} from '../../../../web/scripts/verify-internal-nonpublication.mjs';
const input=JSON.parse(readFileSync(resolve(import.meta.dirname,'../fixtures/synthetic-input.json'))),key=input.key,obsKey='SYNTHETIC-OBSERVATION-KEY-000000000000000000';input.tenant_id=input.trusted_context.tenant_id;const tc=input.trusted_context;
const trusted_keys={[input.key_id]:{status:'active',key}},observation_keys={'obs-key-1':{status:'active',key:obsKey}},registered_apps={'tenant-synthetic-a\0app-synthetic-a\0synthetic-1.0':{status:'active'}},presentation_keys=trusted_keys;
const fixtureIssue=()=>issuePresentation({...input,fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'});
const recordRevision=sha256(canonicalSafetyBytes(input.record)),metadataDigest=sha256(Buffer.from(fixtureIssue().presentation_metadata.opaque_canary));const metadata_registry={[metadataDigest]:{status:'active',metadata_type:'canary',tenant_id:input.tenant_id,app_id:'app-synthetic-a',app_version:'synthetic-1.0',record_revision:recordRevision,release_revision:input.release_revision,issuance_key_id:input.key_id}};
const ledgerFor=e=>({[sha256(Buffer.from(e.presentation_token))]:{status:'active',tenant_id:input.tenant_id,app_id:'app-synthetic-a',app_version:'synthetic-1.0',record_revision:recordRevision,issued_at:e.issued_at,expires_at:e.expires_at,key_id:e.key_id}});
const artifactDigest=sha256(Buffer.from('artifact')),acquisition_registry={'build-synthetic-1':{status:'active',artifact_sha256:artifactDigest,acquisition_provenance:'registered_capture_service',scan_method:'static_digest_scan_v1',scan_version:'1'},'a1':{status:'active',artifact_sha256:sha256(Buffer.from('a')),acquisition_provenance:'licensed_store_artifact',scan_method:'static_digest_scan_v1',scan_version:'1'}},scan_version_registry={[`static_digest_scan_v1\0${'1'}`]:{status:'active'}};
const store=()=>{const seen=new Set();return{calls:[],claim(x){this.calls.push(x);const keys=x.claims.map(c=>`${x.scope.tenant_id}\0${x.scope.key_id}\0${c.type}\0${c.value}`);if(keys.some(k=>seen.has(k)))return false;keys.forEach(k=>seen.add(k));return true;}}};
const verify=(e,replay_store)=>verifyPresentation(e,{trusted_keys,trusted_context:tc,release_revision:input.release_revision,now:'2026-08-17T10:01:00.000Z',replay_store});
const canonical=v=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
const resign=e=>({...e,presentation_token:createHmac('sha256',key).update(canonical(Object.fromEntries(Object.entries(e).filter(([name])=>name!=='presentation_token')))).digest('base64url')});
const treeStats=value=>{const stats={nodes:0,bytes:0,maxDepth:0,maxWidth:0,maxArray:0},visit=(node,depth)=>{stats.nodes++;stats.maxDepth=Math.max(stats.maxDepth,depth);if(typeof node==='string')stats.bytes+=Buffer.byteLength(node);else if(Array.isArray(node)){stats.maxArray=Math.max(stats.maxArray,node.length);node.forEach(child=>visit(child,depth+1));}else if(node&&typeof node==='object'){stats.maxWidth=Math.max(stats.maxWidth,Object.keys(node).length);for(const [name,child] of Object.entries(node)){stats.bytes+=Buffer.byteLength(name);visit(child,depth+1);}}};visit(value,0);return stats;};
const utf8Bytes=bytes=>'😀'.repeat(Math.floor(bytes/4))+(bytes%4===3?'界':bytes%4===2?'é':bytes%4===1?'a':'');
test('random nonces differ at the same time; fixture nonce is explicit and guarded',()=>{const {fixture_nonce,_synthetic,...production}=input,a=issuePresentation(production),b=issuePresentation(production);assert.notEqual(a.response_nonce,b.response_nonce);assert.notEqual(a.presentation_token,b.presentation_token);assert.deepEqual(fixtureIssue(),fixtureIssue());assert.throws(()=>issuePresentation({...input,synthetic_fixture:false,fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'}),/synthetic_fixture:true/);assert.equal('response_counter' in a,false);});
test('persistent atomic replay contract is mandatory, scoped, retained through expiry plus skew, and shared replay fails',()=>{const e=fixtureIssue();assert.throws(()=>verify(e),/replay store required/);const shared=store();const v=verify(e,shared);assert.deepEqual(v.scope,{tenant_id:input.tenant_id,key_id:input.key_id});assert.equal(v.retain_until,'2026-08-17T10:02:05.000Z');assert.deepEqual(shared.calls[0].claims.map(x=>x.type),['token','nonce']);assert.throws(()=>verify(e,shared),/replay claim rejected/);assert.throws(()=>verify(e,{claim(){throw Error('down')}}),/failed closed/);});
test('presentation trust, bindings, expiry, and safety byte identity fail closed',()=>{const e=fixtureIssue();assert.deepEqual(canonicalSafetyBytes(e.canonical_record),canonicalSafetyBytes(input.record));assert.equal(verify(e,store()).valid,true);assert.throws(()=>verifyPresentation(e,{trusted_keys:{x:{status:'active',key}},trusted_context:tc,release_revision:input.release_revision,now:input.now,replay_store:store()}),/unknown presentation key/);assert.throws(()=>verifyPresentation(e,{trusted_keys:{[input.key_id]:{status:'revoked',key}},trusted_context:tc,release_revision:input.release_revision,now:input.now,replay_store:store()}),/revoked/);assert.throws(()=>verify({...e,canonical_record:{...e.canonical_record,provider_identity:'tampered'}},store()),/record binding/);assert.throws(()=>verify({...e,presentation_token:`A${e.presentation_token.slice(1)}`},store()),/signature/);assert.throws(()=>verifyPresentation(e,{trusted_keys,trusted_context:{...tc,tenant_id:'other'},release_revision:input.release_revision,now:input.now,replay_store:store()}),/scope binding/);assert.throws(()=>verifyPresentation(e,{trusted_keys,trusted_context:tc,release_revision:input.release_revision,now:e.expires_at,replay_store:store()}),/expired/);});
test('presentation lifetime maximum has an exact inclusive 300-second boundary',()=>{assert.equal(PRESENTATION_MAX_TTL_SECONDS,300);const exact=issuePresentation({...input,ttl_seconds:PRESENTATION_MAX_TTL_SECONDS,fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'});assert.equal(exact.expires_at,'2026-08-17T10:05:00.000Z');assert.equal(verify(exact,store()).valid,true);assert.throws(()=>issuePresentation({...input,ttl_seconds:PRESENTATION_MAX_TTL_SECONDS+1}),/ttl_seconds invalid integer/);});
test('multilingual safety strings use bounded UTF-8 bytes, including combining and astral text',()=>{const withText=value=>({...input.record,provider_identity:value});for(const value of ['界'.repeat(53)+'a',('e\u0301').repeat(53)+'a','😀'.repeat(40)]){assert.equal(Buffer.byteLength(value),160);assert.doesNotThrow(()=>canonicalSafetyBytes(withText(value)));}for(const value of ['界'.repeat(54),('e\u0301').repeat(53)+'é','😀'.repeat(40)+'a']){assert.ok(Buffer.byteLength(value)>160);assert.throws(()=>canonicalSafetyBytes(withText(value)),/invalid text/);}const at64='😀'.repeat(16),above64=at64+'a';assert.equal(Buffer.byteLength(at64),64);assert.doesNotThrow(()=>issuePresentation({...input,trusted_context:{...tc,app_version:at64}}));assert.throws(()=>issuePresentation({...input,trusted_context:{...tc,app_version:above64}}),/app_version invalid text/);});
test('completed signed envelope enforces exact recursive boundaries including wrapper overhead',()=>{const fields=['callable_numbers','sms_codes','contact_urls','contact_emails'],lengths=[100,100,29,1],record={...input.record};for(const [index,field] of fields.entries())record[field]=Array(lengths[index]).fill('a');const exactNodes=issuePresentation({...input,record});assert.deepEqual(treeStats(exactNodes),{nodes:256,bytes:1089,maxDepth:3,maxWidth:13,maxArray:100});assert.throws(()=>issuePresentation({...input,record:{...record,contact_emails:['a','a']}}),/envelope too many nodes/);assert.doesNotThrow(()=>issuePresentation({...input,record:{...input.record,callable_numbers:Array(100).fill('a')}}));assert.throws(()=>issuePresentation({...input,record:{...input.record,callable_numbers:Array(101).fill('a')}}),/invalid array|oversized array/);const width=value=>{const e={...fixtureIssue()};for(let index=0;index<value-13;index++)e[`extra_${index}`]='a';return e;};assert.equal(Object.keys(width(32)).length,32);assert.throws(()=>verify(width(32),store()),/unknown field/);assert.throws(()=>verify(width(33),store()),/object too wide/);const depth5={...fixtureIssue(),canonical_record:{...input.record,callable_numbers:[[['a']]]}},depth6={...fixtureIssue(),canonical_record:{...input.record,callable_numbers:[[[['a']]]]}};assert.equal(treeStats(depth5).maxDepth,5);assert.throws(()=>verify(depth5,store()),/invalid array/);assert.throws(()=>verify(depth6,store()),/nesting too deep/);});
test('completed envelope aggregate UTF-8 limit includes metadata and token wrapper overhead',()=>{const fields=['callable_numbers','sms_codes','contact_urls','contact_emails'],lengths=[100,100,29,1],record={...input.record};let remaining=31909,used=0;for(const [fieldIndex,field] of fields.entries()){record[field]=Array.from({length:lengths[fieldIndex]},()=>{const bytes=Math.min(160,remaining-(230-used-1));remaining-=bytes;used++;return utf8Bytes(bytes);});}assert.equal(remaining,0);const exact=issuePresentation({...input,record});assert.equal(treeStats(exact).bytes,32768);const above={...record,contact_emails:[`${record.contact_emails[0]}a`]};assert.throws(()=>issuePresentation({...input,record:above}),/envelope aggregate bytes exceeded/);});
test('release revision has signed alternate-issuer UTF-8 boundary and verifier parity',()=>{for(const release_revision of ['界'.repeat(53)+'a','😀'.repeat(40)]){assert.equal(Buffer.byteLength(release_revision),160);const e=issuePresentation({...input,release_revision});assert.equal(verifyPresentation(e,{trusted_keys,trusted_context:tc,release_revision,now:'2026-08-17T10:01:00.000Z',replay_store:store()}).valid,true);}const over='😀'.repeat(40)+'a',signed=resign({...fixtureIssue(),release_revision:over});assert.equal(Buffer.byteLength(over),161);assert.throws(()=>verifyPresentation(signed,{trusted_keys,trusted_context:tc,release_revision:over,now:'2026-08-17T10:01:00.000Z',replay_store:store()}),/release_revision invalid text/);assert.throws(()=>issuePresentation({...input,release_revision:over}),/release_revision invalid text/);});
test('presentation MAC precedes derived metadata comparison and replay claim',()=>{const e=fixtureIssue(),replay=store(),tampered={...e,presentation_metadata:{...e.presentation_metadata,opaque_alias:`A${e.presentation_metadata.opaque_alias.slice(1)}`}};assert.throws(()=>verify(tampered,replay),/invalid signature/);assert.equal(replay.calls.length,0);});
test('opaque metadata and digests are app/version scoped without changing safety bytes',()=>{const a=fixtureIssue(),forApp=app_id=>issuePresentation({...input,trusted_context:{...tc,app_id},fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'}),forVersion=app_version=>issuePresentation({...input,trusted_context:{...tc,app_version},fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'}),b=forApp('app-synthetic-b'),v=forVersion('synthetic-2.0');for(const other of [b,v]){assert.notEqual(a.presentation_metadata.opaque_alias,other.presentation_metadata.opaque_alias);assert.notEqual(a.presentation_metadata.opaque_canary,other.presentation_metadata.opaque_canary);assert.notEqual(sha256(Buffer.from(a.presentation_metadata.opaque_alias)),sha256(Buffer.from(other.presentation_metadata.opaque_alias)));assert.notEqual(sha256(Buffer.from(a.presentation_metadata.opaque_canary)),sha256(Buffer.from(other.presentation_metadata.opaque_canary)));assert.deepEqual(canonicalSafetyBytes(a.canonical_record),canonicalSafetyBytes(other.canonical_record));assert.equal(a.record_revision,other.record_revision);}});
function sign(kind,body){const e=fixtureIssue(),bound=['render','presentation'].includes(kind)?{record_revision:recordRevision,presentation_status:'active',presentation_issued_at:e.issued_at,presentation_expires_at:e.expires_at,issuance_key_id:e.key_id}:{};return signSyntheticEvidence(kind,{...bound,...body},{synthetic_fixture:true,evidence_key_id:'obs-key-1',evidence_key:obsKey});}
const base={observation_id:'obs-1',tenant_id:input.tenant_id,app_id:'app-synthetic-a',app_version:'synthetic-1.0'};
const ctx=e=>({observation_keys,registered_apps,presentation_ledger:ledgerFor(e),metadata_registry,presentation_keys,acquisition_registry,scan_version_registry});
test('all evidence is signed, domain separated, app registered, and presentation-ledger bound',()=>{const e=fixtureIssue(),c=ctx(e),pd=sha256(Buffer.from(e.presentation_token));const render=sign('render',{...base,presentation_token_digest:pd,record_revision:recordRevision,coarse_time_bucket:'2026-08-17T10:00:00.000Z',render_count:2});assert.equal(validateRenderAttestation(render,c).tenant_id,input.tenant_id);assert.throws(()=>validateRenderAttestation({...render,render_count:3},c),/signature/);assert.throws(()=>validateFetchObservation(render,c),/unknown field|domain/);assert.throws(()=>validateRenderAttestation(render,{...c,observation_keys:{'obs-key-1':{status:'revoked',key:obsKey}}}),/revoked/);assert.throws(()=>validateRenderAttestation(render,{...c,registered_apps:{}}),/registry invalid|unknown/);assert.throws(()=>validateRenderAttestation(render,{...c,presentation_ledger:{[pd]:{...ledgerFor(e)[pd],app_id:'other'}}}),/binding mismatch/);});
test('presentation ledger binds every issuance field, validity interval, and active issuance key',()=>{const e=fixtureIssue(),c=ctx(e),pd=sha256(Buffer.from(e.presentation_token)),body={...base,presentation_token_digest:pd,surface_class:'licensed_app',observed_at:'2026-08-17T10:01:00.000Z'};assert.equal(validatePresentationObservation(sign('presentation',body),c).issuance_key_id,input.key_id);for(const field of ['tenant_id','app_id','app_version','record_revision','issued_at','expires_at','key_id']){const entry={...ledgerFor(e)[pd],[field]:field.endsWith('_at')?'2026-08-17T09:00:00.000Z':'substituted'};assert.throws(()=>validatePresentationObservation(sign('presentation',body),{...c,presentation_ledger:{[pd]:entry}}));}assert.throws(()=>validatePresentationObservation(sign('presentation',{...body,observed_at:'2026-08-17T09:59:59.000Z'}),c),/before issuance/);assert.throws(()=>validatePresentationObservation(sign('presentation',{...body,observed_at:e.expires_at}),c),/at or after expiry/);assert.throws(()=>validatePresentationObservation(sign('presentation',body),{...c,presentation_keys:{[input.key_id]:{status:'revoked',key}}}),/revoked/);});
test('ledger-backed presentation and render evidence enforce canonical bounded lifetimes',()=>{const e=fixtureIssue(),pd=sha256(Buffer.from(e.presentation_token)),original=ledgerFor(e)[pd];const validateLedger=(entry,{observed_at='2026-08-17T10:04:59.000Z',coarse_time_bucket='2026-08-17T10:00:00.000Z'}={})=>{const c={...ctx(e),presentation_ledger:{[pd]:entry}},bound={...base,presentation_token_digest:pd,presentation_issued_at:entry.issued_at,presentation_expires_at:entry.expires_at};const presentation=sign('presentation',{...bound,surface_class:'licensed_app',observed_at}),render=sign('render',{...bound,record_revision:recordRevision,coarse_time_bucket,render_count:1});return{presentation:()=>validatePresentationObservation(presentation,c),render:()=>validateRenderAttestation(render,c)};};const exact={...original,issued_at:'2026-08-17T10:00:00.000Z',expires_at:'2026-08-17T10:05:00.000Z'};for(const validate of Object.values(validateLedger(exact)))assert.doesNotThrow(validate);const invalid=[['alternate 300.001-second ledger',{...exact,expires_at:'2026-08-17T10:05:00.001Z'}],['alternate 301-second ledger',{...exact,expires_at:'2026-08-17T10:05:01.000Z'}],['stale overlong ledger',{...exact,issued_at:'2026-08-16T10:00:00.000Z',expires_at:'2026-08-16T10:05:01.000Z'}],['equal timestamps',{...exact,expires_at:exact.issued_at}],['reversed timestamps',{...exact,issued_at:'2026-08-17T10:05:00.000Z',expires_at:'2026-08-17T10:00:00.000Z'}],['normalizing timestamp',{...exact,issued_at:'2026-08-17T10:00:00Z'}],['calendar-rollover timestamp',{...exact,issued_at:'2026-02-30T10:00:00.000Z'}],['leap-second timestamp',{...exact,issued_at:'2026-08-17T09:59:60.000Z'}]];for(const [label,entry] of invalid)for(const [kind,validate] of Object.entries(validateLedger(entry)))assert.throws(validate,/invalid (?:timestamp|lifetime)/,`${label} accepted for ${kind}`);});
test('runtime rejects leap seconds in every schema-backed timestamp role',()=>{const leap='2026-08-17T10:00:60.000Z',e=fixtureIssue(),c=ctx(e),pd=sha256(Buffer.from(e.presentation_token));assert.throws(()=>issuePresentation({...input,now:leap}),/invalid now/);for(const field of ['issued_at','expires_at'])assert.throws(()=>verify(resign({...e,[field]:leap}),store()),/invalid timestamp/,field);const body={...base,presentation_token_digest:pd,surface_class:'licensed_app',observed_at:'2026-08-17T10:01:00.000Z'};for(const field of ['presentation_issued_at','presentation_expires_at','observed_at'])assert.throws(()=>validatePresentationObservation(sign('presentation',{...body,[field]:leap}),c),/invalid timestamp/,field);const render={...base,presentation_token_digest:pd,record_revision:recordRevision,coarse_time_bucket:'2026-08-17T10:00:00.000Z',render_count:1};for(const field of ['presentation_issued_at','presentation_expires_at'])assert.throws(()=>validateRenderAttestation(sign('render',{...render,[field]:leap}),c),/invalid timestamp/,field);});
test('schema enums are enforced at runtime and signed free-form values fail',()=>{const e=fixtureIssue(),c=ctx(e),pd=sha256(Buffer.from(e.presentation_token));assert.throws(()=>validatePresentationObservation(sign('presentation',{...base,presentation_token_digest:pd,surface_class:'covert-channel',observed_at:'2026-08-17T10:01:00.000Z'}),c),/surface_class invalid enum/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,surface_class:'signed-free-form'}),c),/surface_class invalid enum/);assert.throws(()=>validateBinaryObservation(sign('binary',{...base,observation_id:'b-enum',artifact_sha256:artifactDigest,platform:'browser',acquisition_provenance:'registered_capture_service',acquisition_id:'build-synthetic-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:null}),c),/platform invalid enum/);});
test('closed fields and strict resource caps run before signature canonicalization',()=>{const e=fixtureIssue(),c=ctx(e),normal=sign('fetch',{...base,coarse_time_bucket:'2026-08-17T10:00:00.000Z',fetch_count:1,unique_token_count:1,conditional_request_count:0,surface_count:1});assert.throws(()=>validateFetchObservation({...normal,unknown:'x'.repeat(50000)},c),/unknown field/);const wide={...normal};for(let i=0;i<40;i++)wide[`x${i}`]=i;assert.throws(()=>validateFetchObservation(wide,c),/object too wide|unknown field/);assert.throws(()=>validateFetchObservation({...normal,app_version:'x'.repeat(40000)},c),/aggregate bytes exceeded/);const deep={...normal,extra:{a:{b:{c:{d:{e:1}}}}}};assert.throws(()=>validateFetchObservation(deep,c),/unknown field/);});
const outwardBody={observation_id:'out-1',artifact_sha256:artifactDigest,acquisition_provenance:'registered_capture_service',acquisition_id:'build-synthetic-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest,surface_class:'third_party_app',coarse_time_bucket:'2026-08-17T10:00:00.000Z',match_count:1};
test('outward match count and metadata digest have an exact positive-or-neutral invariant',()=>{const c=ctx(fixtureIssue());assert.equal(validateOutwardObservation(sign('outward',outwardBody),c).match_count,1);assert.equal(validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-neutral',matched_metadata_digest:null,match_count:0}),c).registry_match,false);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-positive-null',matched_metadata_digest:null,match_count:1}),c),/count and metadata digest mismatch/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-zero-digest',match_count:0}),c),/count and metadata digest mismatch/);});
test('outward capture attribution requires registered artifact provenance; authenticated non-match is neutral',()=>{const e=fixtureIssue(),c=ctx(e),v=validateOutwardObservation(sign('outward',outwardBody),c);assert.equal(v.tenant_id,input.tenant_id);assert.equal(v.metadata_type,'canary');const none=validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-none',matched_metadata_digest:null,match_count:0}),c);assert.equal(none.registry_match,false);assert.equal(analyzeCompliance({outward:[none]}).signals[0].code,'insufficient_evidence');assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,artifact_sha256:sha256(Buffer.from('tamper'))}),c),/acquisition registry binding/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,matched_metadata_digest:sha256(Buffer.from('unknown'))}),c),/unknown issued metadata/);assert.throws(()=>validateOutwardObservation(sign('outward',outwardBody),{...c,metadata_registry:{[metadataDigest]:{...metadata_registry[metadataDigest],status:'revoked'}}}),/revoked/);});
test('outward alias and canary provenance stay registry-derived, frozen, and type-specific in analysis',()=>{const e=fixtureIssue(),aliasDigest=sha256(Buffer.from(e.presentation_metadata.opaque_alias)),aliasEntry={...metadata_registry[metadataDigest],metadata_type:'alias'},c={...ctx(e),metadata_registry:{...metadata_registry,[aliasDigest]:aliasEntry}},alias=validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-alias',matched_metadata_digest:aliasDigest}),c),canary=validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-canary'}),c);assert.equal(alias.metadata_type,'alias');assert.equal(canary.metadata_type,'canary');assert.equal(Object.isFrozen(alias),true);assert.throws(()=>{alias.metadata_type='canary';},TypeError);const aliasCodes=analyzeCompliance({outward:[alias]}).signals.map(signal=>signal.code);assert.deepEqual(aliasCodes,['outward_in_alias_match']);assert.equal(aliasCodes.includes('outward_in_canary_match'),false);assert.deepEqual(analyzeCompliance({outward:[canary]}).signals.map(signal=>signal.code),['outward_in_canary_match']);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'observer-type',metadata_type:'canary',matched_metadata_digest:aliasDigest}),c),/unknown field/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'tampered-type',matched_metadata_digest:aliasDigest}),{...c,metadata_registry:{[aliasDigest]:{...aliasEntry,metadata_type:'canary'}}}),/derivation mismatch/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'revoked-alias',matched_metadata_digest:aliasDigest}),{...c,metadata_registry:{[aliasDigest]:{...aliasEntry,status:'revoked'}}}),/revoked/);});
test('metadata registry proves derivation before outward attribution or binary acceptance',()=>{const e=fixtureIssue(),c=ctx(e),otherApp='app-synthetic-b',otherVersion='synthetic-2.0',apps={...registered_apps,[`${input.tenant_id}\0${otherApp}\0synthetic-1.0`]:{status:'active'},[`${input.tenant_id}\0app-synthetic-a\0${otherVersion}`]:{status:'active'}};for(const patch of [{app_id:otherApp},{app_version:otherVersion}]){const poisoned={...metadata_registry[metadataDigest],...patch},bad={...c,registered_apps:apps,metadata_registry:{[metadataDigest]:poisoned}};assert.throws(()=>validateOutwardObservation(sign('outward',outwardBody),bad),/derivation mismatch/);const binary={...base,observation_id:`bin-cross-${patch.app_id||patch.app_version}`,artifact_sha256:artifactDigest,platform:'ios',acquisition_provenance:'registered_capture_service',acquisition_id:'build-synthetic-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest};assert.throws(()=>validateBinaryObservation(sign('binary',binary),bad),/derivation mismatch/);}const other=issuePresentation({...input,trusted_context:{...tc,app_id:otherApp},fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'}),otherDigest=sha256(Buffer.from(other.presentation_metadata.opaque_canary)),registry={...metadata_registry,[otherDigest]:{...metadata_registry[metadataDigest],app_id:otherApp}},otherContext={...c,registered_apps:apps,metadata_registry:registry};const outward=validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-other',matched_metadata_digest:otherDigest}),otherContext);assert.equal(outward.app_id,otherApp);const cross={...base,observation_id:'bin-cross-valid',artifact_sha256:artifactDigest,platform:'ios',acquisition_provenance:'registered_capture_service',acquisition_id:'build-synthetic-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:otherDigest};assert.throws(()=>validateBinaryObservation(sign('binary',cross),otherContext),/app binding mismatch/);const correctlyScoped=sign('binary',{...cross,observation_id:'bin-other-valid',app_id:otherApp});assert.equal(validateBinaryObservation(correctlyScoped,otherContext).registry_match,true);});
test('privacy-safe binary observation supports match/non-match and rejects tamper/mismatch',()=>{const e=fixtureIssue(),c=ctx(e);const body={...base,observation_id:'bin-1',artifact_sha256:artifactDigest,platform:'ios',acquisition_provenance:'registered_capture_service',acquisition_id:'build-synthetic-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest};const match=validateBinaryObservation(sign('binary',body),c);assert.equal(match.matched_metadata_digest,metadataDigest);const none=validateBinaryObservation(sign('binary',{...body,observation_id:'bin-2',matched_metadata_digest:null}),c);assert.equal(none.registry_match,false);assert.throws(()=>validateBinaryObservation({...sign('binary',body),platform:'android'},c),/signature/);assert.throws(()=>validateBinaryObservation(sign('binary',{...body,app_id:'other'}),c),/registered app/);assert.equal(JSON.stringify(body).includes('callable_numbers'),false);});
function vf(hour,count,idSuffix='x'){return validateFetchObservation(sign('fetch',{...base,observation_id:`f-${hour.slice(11,13)}-${idSuffix}`,coarse_time_bucket:hour,fetch_count:count,unique_token_count:Math.min(count,1),conditional_request_count:0,surface_count:1}),ctx(fixtureIssue()));}
test('calendar hours require canonical UTC round-trip equality',()=>{assert.equal(vf('2024-02-29T10:00:00.000Z',1,'leap').coarse_time_bucket,'2024-02-29T10:00:00.000Z');assert.equal(vf('2026-02-28T10:00:00.000Z',1,'valid').coarse_time_bucket,'2026-02-28T10:00:00.000Z');for(const value of ['2026-02-30T10:00:00.000Z','2025-02-29T10:00:00.000Z'])assert.throws(()=>vf(value,1,'invalid'),/valid UTC hour/);const c=ctx(fixtureIssue());assert.throws(()=>validateRenderAttestation(sign('render',{...base,presentation_token_digest:sha256(Buffer.from(fixtureIssue().presentation_token)),coarse_time_bucket:'2026-02-30T10:00:00.000Z',render_count:1}),c),/valid UTC hour/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,coarse_time_bucket:'2026-02-30T10:00:00.000Z'}),c),/valid UTC hour/);});
test('analysis requires exact deeply-frozen verified identity and rejects spread, clone, and modification',()=>{const v=vf('2026-08-17T10:00:00.000Z',1);assert.ok(Object.isFrozen(v));assert.throws(()=>{v.nested={};},TypeError);for(const x of [{...v},structuredClone(v),{...v,fetch_count:999}])assert.throws(()=>analyzeCompliance({fetches:[x]}),/exact verified/);});
function analysisEvidence(){const e=fixtureIssue(),c=ctx(e),pd=sha256(Buffer.from(e.presentation_token));return{presentations:validatePresentationObservation(sign('presentation',{...base,observation_id:'analysis-presentation',presentation_token_digest:pd,surface_class:'licensed_app',observed_at:'2026-08-17T10:01:00.000Z'}),c),renders:validateRenderAttestation(sign('render',{...base,observation_id:'analysis-render',presentation_token_digest:pd,record_revision:recordRevision,coarse_time_bucket:'2026-08-17T10:00:00.000Z',render_count:2}),c),fetches:validateFetchObservation(sign('fetch',{...base,observation_id:'analysis-fetch',coarse_time_bucket:'2026-08-17T10:00:00.000Z',fetch_count:100,unique_token_count:100,conditional_request_count:1,surface_count:1}),c),outward:validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'analysis-outward'}),c),binaries:validateBinaryObservation(sign('binary',{...base,observation_id:'analysis-binary',artifact_sha256:artifactDigest,platform:'ios',acquisition_provenance:'registered_capture_service',acquisition_id:'build-synthetic-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest}),c)};}
test('analysis rejects every pairwise wrong-bucket placement before deriving signals',()=>{const evidence=analysisEvidence(),buckets=Object.keys(evidence);for(const source of buckets)for(const target of buckets)if(source!==target)assert.throws(()=>analyzeCompliance({[target]:[evidence[source]]}),new RegExp(`${target} requires`),`${source} accepted in ${target}`);});
test('analysis fails closed for mixed arrays, duplicate ids, unknown buckets, mutated sources, and lookalikes',()=>{const evidence=analysisEvidence();assert.throws(()=>analyzeCompliance({fetches:[evidence.fetches,evidence.renders]}),/fetches requires fetch evidence/);assert.throws(()=>analyzeCompliance({fetches:[evidence.fetches],renders:[evidence.fetches]}),/renders requires render evidence/);assert.throws(()=>analyzeCompliance({fetches:[evidence.fetches,evidence.fetches]}),/duplicate observation_id/);assert.throws(()=>analyzeCompliance({fetches:[evidence.fetches],mystery:[]}),/unknown bucket/);assert.throws(()=>analyzeCompliance({fetches:[{...evidence.fetches}]}),/exact verified/);const signed=sign('fetch',{...base,observation_id:'mutated-source',coarse_time_bucket:'2026-08-17T10:00:00.000Z',fetch_count:1,unique_token_count:1,conditional_request_count:0,surface_count:1}),verified=validateFetchObservation(signed,ctx(fixtureIssue()));signed.evidence_type='render';assert.throws(()=>analyzeCompliance({fetches:[signed]}),/exact verified/);assert.equal(verified.evidence_type,'fetch');assert.throws(()=>{verified.evidence_type='render';},TypeError);});
test('correctly bucketed verified evidence preserves existing analysis signals',()=>{const evidence=analysisEvidence(),result=analyzeCompliance(Object.fromEntries(Object.entries(evidence).map(([bucket,observation])=>[bucket,[observation]]))),codes=new Set(result.signals.map(signal=>signal.code));for(const code of ['bounded_render_fetch_ratio','bulk_sweep','conditional_requests_despite_no_store','outward_in_canary_match','app_binary_metadata_match'])assert.ok(codes.has(code),`missing ${code}`);assert.equal(result.assessment,'corroborating_only_not_conclusive');});
test('flat volume aggregates distinct hours and requires equal positive consecutive run',()=>{const h=n=>`2026-08-17T${String(n).padStart(2,'0')}:00:00.000Z`,flat=a=>analyzeCompliance({fetches:a}).signals.some(s=>s.code==='flat_volume_pattern');assert.equal(flat([vf(h(10),1,'a'),vf(h(10),1,'b'),vf(h(10),1,'c')]),false,'duplicates are one bucket');assert.equal(flat([vf(h(10),2),vf(h(12),2),vf(h(13),2)]),false,'gap');assert.equal(flat([vf(h(10),2),vf(h(11),3),vf(h(12),2)]),false,'non-equal');assert.equal(flat([vf(h(10),2),vf(h(11),2),vf(h(12),2)]),true,'valid run');assert.equal(flat([vf(h(10),1,'a'),vf(h(10),1,'b'),vf(h(11),2),vf(h(12),2)]),true,'same-hour aggregation');});
test('app versions are incomparable in ratios and flat-volume series',()=>{const h=n=>`2026-08-17T${String(n).padStart(2,'0')}:00:00.000Z`,otherRegistry={...registered_apps,'tenant-synthetic-a\0app-synthetic-a\0synthetic-2.0':{status:'active'}},make=(n,version)=>validateFetchObservation(sign('fetch',{...base,app_version:version,observation_id:`cv-${n}-${version}`,coarse_time_bucket:h(n),fetch_count:2,unique_token_count:1,conditional_request_count:0,surface_count:1}),{...ctx(fixtureIssue()),registered_apps:otherRegistry});const r=analyzeCompliance({fetches:[make(10,'synthetic-1.0'),make(11,'synthetic-2.0'),make(12,'synthetic-1.0')]});assert.equal(r.signals.some(x=>x.code==='flat_volume_pattern'),false);assert.ok(r.signals.filter(x=>x.code==='missing_render_attestation').every(x=>x.detail.app_version));});
test('corroborating evidence remains non-conclusive',()=>{const e=fixtureIssue(),c=ctx(e);const out=validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-z',surface_class:'public_web'}),c);const bin=validateBinaryObservation(sign('binary',{...base,observation_id:'bin-z',artifact_sha256:sha256(Buffer.from('a')),platform:'ios',acquisition_provenance:'licensed_store_artifact',acquisition_id:'a1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest}),c);const r=analyzeCompliance({outward:[out],binaries:[bin]});assert.ok(r.signals.every(s=>s.conclusive===false));assert.equal(r.assessment,'corroborating_only_not_conclusive');});
test('nonpublication rejects marker-stripped licensed semantic subtree and counsel excerpt',()=>{const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-nonpub-')),dist=resolve(root,'dist');mkdirSync(dist);try{const http=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/http-contract.json')));writeFileSync(resolve(dist,'subtree.json'),JSON.stringify(http.replay));assert.throws(()=>assertInternalNonpublication(dist,repo),/semantic section|scalar fingerprint/);rmSync(dist,{recursive:true});mkdirSync(dist);const terms=readFileSync(resolve(repo,'reviews/licensed-delivery/v1/terms.counsel-draft.md'),'utf8'),excerpt=terms.split(/\n\s*\n/).find(x=>x.includes('Replay prevention requires'));writeFileSync(resolve(dist,'draft.txt'),excerpt.replace(/\s+/g,' ').trim());assert.throws(()=>assertInternalNonpublication(dist,repo),/scalar fingerprint/);}finally{rmSync(root,{recursive:true,force:true});}});
test('nonpublication rejects normalized licensed schema and HTTP contract scalars',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-contract-nonpub-'));
  const schema='Internal licensed-delivery v1 closed schema bundle',http='future_authenticated_runtime_contract_not_active';
  const percent=value=>[...Buffer.from(value)].map(byte=>`%${byte.toString(16).padStart(2,'0')}`).join('');
  const entities=value=>[...value].map(character=>`&#${character.codePointAt(0)};`).join('');
  const js=value=>[...value].map(character=>`\\u${character.codePointAt(0).toString(16).padStart(4,'0')}`).join('');
  const split=value=>{const at=Math.floor(value.length/2);return `${value.slice(0,at)}<span></span>${value.slice(at)}`;};
  const cases=[
    ['schema-raw.txt',schema],
    ['http-extracted.json',JSON.stringify({public:true,value:http},null,3)],
    ['schema-entity.txt',entities(schema)],
    ['http-percent.txt',percent(http)],
    ['schema-js.txt',js(schema)],
    ['schema-nested.txt','internal\\u0026#45;licensed'+entities(' delivery v1 closed schema bundle')],
    ['schema-text.html',`<main>${schema}</main>`],
    ['http-split.html',`<p>${split(http)}</p>`],
    ['schema-attribute.html',`<meta content="${entities(percent(schema))}">`],
    ['http-attribute.htm',`<div data-contract='${js(http)}'></div>`],
  ];
  try{
    for(const [name,content] of cases){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.throws(()=>assertInternalNonpublication(dist,repo),/licensed-delivery contract scalar fingerprint/,name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('nonpublication semantically rejects every licensed synthetic fixture and substantive branch',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),fixturesRoot=resolve(repo,'reviews/licensed-delivery/v1/fixtures'),root=mkdtempSync(resolve(tmpdir(),'licensed-fixture-nonpub-'));
  const fixtures=['synthetic-input.json','presentation.synthetic.json','observations.synthetic.json'].map(name=>[name,JSON.parse(readFileSync(resolve(fixturesRoot,name),'utf8'))]);
  const reordered=value=>Array.isArray(value)?value.map(reordered):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).reverse().map(([key,child])=>[key,reordered(child)])):value;
  const assertRejected=(label,value,pattern=/semantic section|scalar fingerprint/)=>{const dist=resolve(root,label.replace(/[^a-z0-9]+/giu,'-'));mkdirSync(dist);writeFileSync(resolve(dist,'transformed.json'),JSON.stringify(reordered(value),null,3));assert.throws(()=>assertInternalNonpublication(dist,repo),pattern,label);};
  try{
    for(const [name,fixture] of fixtures){
      assertRejected(`${name}-whole`,fixture,/internal (?:review-pack marker|evidence exact copy|review-pack semantic section|review-pack scalar fingerprint|licensed-delivery (?:contract|fixture) scalar fingerprint)/);
      const stripped=structuredClone(fixture);delete stripped.synthetic_fixture;if('key'in stripped)stripped.key='ordinary-public-placeholder';assertRejected(`${name}-marker-stripped`,stripped);
      for(const [branch,value] of Object.entries(fixture))if(value&&typeof value==='object')assertRejected(`${name}-${branch}`,value);
    }
    for(const [index,value] of [{status:'active',items:[{label:'Public directory entry',count:2}]},{evidence_type:'public-feedback',platform:'web',message:'Ordinary public JSON.'}].entries()){
      const dist=resolve(root,`control-${index}`);mkdirSync(dist);writeFileSync(resolve(dist,'public.json'),JSON.stringify(value,null,2));assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo));
    }
    const textDist=resolve(root,'text-control');mkdirSync(textDist);writeFileSync(resolve(textDist,'public.txt'),'Public hotline directory information and application help.');assert.doesNotThrow(()=>assertInternalNonpublication(textDist,repo));
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('nonpublication rejects rendered, encoded, and normalized counsel-draft paragraphs without matching common fragments',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-draft-nonpub-'));
  const terms=readFileSync(resolve(repo,'reviews/licensed-delivery/v1/terms.counsel-draft.md'),'utf8');
  const excerpt=terms.split(/\n\s*\n/).find(x=>x.includes('Responses and presentation tokens')).replace(/\s+/g,' ').trim();
  const rejects=[
    ['rendered.html',excerpt.replace(/`([^`]+)`/gu,'<code>$1</code>')],
    ['entities.txt',[...excerpt].map(character=>`&#x${character.codePointAt(0).toString(16)};`).join('')],
    ['split.html',excerpt.toUpperCase().replace('PRESENTATION TOKENS','PRESENTATION <em>TOK</em>ENS')],
  ];
  try{
    for(const [name,content] of rejects){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.throws(()=>assertInternalNonpublication(dist,repo),/scalar fingerprint/,name);}
    for(const [index,content] of ['Authorized application content for a public visitor.','A presentation token may be used by an application.','private no-store max-age 0'].entries()){const dist=resolve(root,`control-${index}`);mkdirSync(dist);writeFileSync(resolve(dist,'public.html'),content);assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo),content);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('nonpublication rejects normalized non-JSON leaks from every licensed fixture evidence branch',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-fixture-rendered-nonpub-'));
  const presentation=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/presentation.synthetic.json')));
  const observations=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/observations.synthetic.json')));
  const percent=value=>[...Buffer.from(value)].map(byte=>`%${byte.toString(16).padStart(2,'0')}`).join('');
  const entities=value=>[...value].map(character=>`&#x${character.codePointAt(0).toString(16)};`).join('');
  const split=value=>{const at=Math.floor(value.length/2);return `${value.slice(0,at)}<span></span>${value.slice(at)}`;};
  const cases=[
    ['outward.html',`<article>${split(observations.outward_observation.evidence_signature)}</article>`],
    ['app-binary.txt',percent(observations.app_binary_observation.evidence_signature)],
    ['presentation.html',`<main>${entities(presentation.envelope.canonical_record.provider_identity)}</main>`],
    ['render.html',`<div>${split(observations.render_attestation.evidence_signature.toUpperCase())}</div>`],
    ['fetch.txt',entities(percent(observations.fetch_observation.evidence_signature))],
  ];
  try{
    for(const [name,content] of cases){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.throws(()=>assertInternalNonpublication(dist,repo),/licensed-delivery fixture scalar fingerprint/,name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('nonpublication rejects encoded licensed fixture scalars in HTML attributes',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-fixture-attribute-nonpub-'));
  const inputFixture=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/synthetic-input.json')));
  const presentation=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/presentation.synthetic.json')));
  const observations=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/observations.synthetic.json')));
  const percent=(value,upper=false)=>[...Buffer.from(value)].map(byte=>`%${byte.toString(16).padStart(2,'0')[upper?'toUpperCase':'toLowerCase']()}`).join('');
  const entities=value=>[...value].map(character=>`&#${character.codePointAt(0)};`).join('');
  const cases=[
    ['entity-key.html',`<DIV DATA-LICENSED="${entities(inputFixture.key)}"></DIV>`],
    ['percent-signature.html',`<span data-evidence='${percent(observations.fetch_observation.evidence_signature)}'></span>`],
    ['upper-percent-digest.htm',`<template DATA-DIGEST=${percent(presentation.envelope.record_revision,true)}></template>`],
    ['nested-encoding.html',`<meta content="${percent(entities(observations.app_binary_observation.evidence_signature))}">`],
  ];
  try{
    for(const [name,content] of cases){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.throws(()=>assertInternalNonpublication(dist,repo),/licensed-delivery fixture scalar fingerprint/,name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('licensed fixture normalized fingerprints permit ordinary artifacts and isolated common values',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-fixture-controls-'));
  const controls=[
    ['public.html','<main><h1>Public hotline directory</h1><p>Current service information for visitors.</p></main>'],
    ['public.txt','Public application help and contact information.'],
    ['public.json',JSON.stringify({status:'active',platform:'ios',updated_at:'2026-08-17T10:00:00.000Z'})],
    ['common.txt','active outward binary presentation render fetch ios registered_capture_service static_digest_scan_v1'],
    ['attributes.html','<section data-status="active" data-platform="ios" aria-label="Public hotline directory" title="Current service information"></section>'],
  ];
  try{
    for(const [name,content] of controls){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo),name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('licensed contract normalized fingerprints permit ordinary and common public content',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-contract-controls-'));
  const controls=[
    ['public.html','<main>Licensed application delivery information for the public.</main>'],
    ['public.txt','A future authenticated service may use a runtime contract after review.'],
    ['public.json',JSON.stringify({cache_control:'private, no-store',schema_version:'1.0',status:'active'})],
    ['attributes.html','<section data-delivery="licensed" data-contract="public" title="Application information"></section>'],
  ];
  try{
    for(const [name,content] of controls){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo),name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
