import test from 'node:test';import assert from 'node:assert/strict';import {createHash,createHmac} from 'node:crypto';import {linkSync,mkdtempSync,mkdirSync,readFileSync,rmSync,symlinkSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {resolve} from 'node:path';import {brotliCompressSync,constants as zlibConstants,gzipSync} from 'node:zlib';
import {HTTP_CONTRACT_METADATA,NORMATIVE_HTTP_CONTRACT,NORMATIVE_HTTP_RESPONSE,PRESENTATION_MAX_TTL_SECONDS,SAFETY_FIELDS,analyzeCompliance,assertNormativeHttpContract,assertNormativeHttpResponse,canonicalSafetyBytes,deriveRecordRevision,issuePresentation,sha256,signSyntheticEvidence,validateBinaryObservation,validateFetchObservation,validateOutwardObservation,validatePresentationObservation,validateRenderAttestation,verifyPresentation} from '../model.mjs';
import {assertInternalNonpublication,classifyHtmlScriptType,decodeArtifactText,decodeLegacyOctalEscapes} from '../../../../web/scripts/verify-internal-nonpublication.mjs';
const input=JSON.parse(readFileSync(resolve(import.meta.dirname,'../fixtures/synthetic-input.json'))),key=input.key,obsKey='SYNTHETIC-OBSERVATION-KEY-000000000000000000';input.tenant_id=input.trusted_context.tenant_id;const tc=input.trusted_context;
const trusted_keys={[input.key_id]:{status:'active',key}},observation_keys={'obs-key-1':{status:'active',key:obsKey}},registered_apps={'tenant-synthetic-a\0app-synthetic-a\0synthetic-1.0':{status:'active'}},presentation_keys=trusted_keys;
const fixtureIssue=()=>issuePresentation({...input,fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'});
const recordRevision=sha256(canonicalSafetyBytes(input.record)),metadataDigest=sha256(Buffer.from(fixtureIssue().presentation_metadata.opaque_canary));const metadata_registry={[metadataDigest]:{status:'active',metadata_type:'canary',tenant_id:input.tenant_id,app_id:'app-synthetic-a',app_version:'synthetic-1.0',record_revision:recordRevision,release_revision:input.release_revision,issuance_key_id:input.key_id}};
const ledgerFor=e=>({[sha256(Buffer.from(e.presentation_token))]:{status:'active',tenant_id:input.tenant_id,app_id:'app-synthetic-a',app_version:'synthetic-1.0',record_revision:recordRevision,issued_at:e.issued_at,expires_at:e.expires_at,key_id:e.key_id}});
const artifactDigest=sha256(Buffer.from('artifact')),binaryAcquisition={status:'active',evidence_type:'binary',tenant_id:input.tenant_id,app_id:'app-synthetic-a',app_version:'synthetic-1.0',platform:'ios',artifact_sha256:artifactDigest,acquisition_provenance:'registered_capture_service',scan_method:'static_digest_scan_v1',scan_version:'1'},acquisition_registry={'build-synthetic-1':{status:'active',evidence_type:'outward',artifact_sha256:artifactDigest,acquisition_provenance:'registered_capture_service',scan_method:'static_digest_scan_v1',scan_version:'1'},'synthetic-build-1':binaryAcquisition,'a1':{...binaryAcquisition,artifact_sha256:sha256(Buffer.from('a')),acquisition_provenance:'licensed_store_artifact'}},scan_version_registry={[`static_digest_scan_v1\0${'1'}`]:{status:'active'}};
const store=()=>{const seen=new Set();return{calls:[],claim(x){this.calls.push(x);const keys=x.claims.map(c=>`${x.scope.tenant_id}\0${x.scope.key_id}\0${c.type}\0${c.value}`);if(keys.some(k=>seen.has(k)))return false;keys.forEach(k=>seen.add(k));return true;}}};
const verify=(e,replay_store)=>verifyPresentation(e,{trusted_keys,trusted_context:tc,release_revision:input.release_revision,now:'2026-08-17T10:01:00.000Z',replay_store});
test('normative HTTP anti-cache response is exact and every control fails closed independently',()=>{const exact={...NORMATIVE_HTTP_RESPONSE};assert.equal(assertNormativeHttpResponse(exact),exact);const changed={cache_control:'no-store',pragma:'no-store',expires:'1',cdn_store_allowed:true,service_worker_store_allowed:true,token_max_ttl_seconds:PRESENTATION_MAX_TTL_SECONDS-1};for(const field of Object.keys(exact)){const removed={...exact};delete removed[field];const mutations=[['changed',{...exact,[field]:changed[field]}],['removed',removed],['null',{...exact,[field]:null}],['wrong-typed',{...exact,[field]:typeof exact[field]==='string'?0:String(exact[field])}]];for(const [kind,value] of mutations)assert.throws(()=>assertNormativeHttpResponse(value),new RegExp(`HTTP response contract (?:invalid ${field}|missing ${field})`),`${field} ${kind}`);}});
test('complete normative HTTP contract is closed and every field fails closed independently',()=>{const exact={...structuredClone(NORMATIVE_HTTP_CONTRACT),...HTTP_CONTRACT_METADATA};assert.equal(assertNormativeHttpContract(exact),exact);const entries=(value,path=[])=>Object.entries(value).flatMap(([key,child])=>{const entry=[[[...path,key],child]];return child&&typeof child==='object'&&!Array.isArray(child)?entry.concat(entries(child,[...path,key])):entry;});const set=(value,path,replacement)=>{const copy=structuredClone(value);let at=copy;for(const key of path.slice(0,-1))at=at[key];if(replacement===undefined)delete at[path.at(-1)];else at[path.at(-1)]=replacement;return copy;};for(const [path,value] of entries(exact)){const label=path.join('.'),changed=Array.isArray(value)?[...value.slice(0,-1),'arbitrary_substitution']:value&&typeof value==='object'?{...value,unexpected:true}:typeof value==='boolean'?!value:typeof value==='number'?value+1:`${value}-changed`;for(const [kind,replacement] of [['changed',changed],['removed',undefined],['null',null],['wrong-type',value&&typeof value==='object'?'wrong':Array.isArray(value)?{}:typeof value==='string'?0:'wrong']])assert.throws(()=>assertNormativeHttpContract(set(exact,path,replacement)),/HTTP contract/,`${label} ${kind}`);}for(const path of [[],['request'],['runtime_trust'],['runtime_trust','acquisition_registry_entry_schemas'],['input_limits'],['schema_runtime_parity'],['replay'],['nonce'],['retention']]){const copy=structuredClone(exact);let at=copy;for(const key of path)at=at[key];at.unexpected=true;assert.throws(()=>assertNormativeHttpContract(copy),/unknown field/,`${path.join('.')||'root'} unknown`);}});
test('contract set fields ignore order but reject duplicates and substitutions',()=>{const exact={...structuredClone(NORMATIVE_HTTP_CONTRACT),...HTTP_CONTRACT_METADATA},paths=[['request','vary'],['runtime_trust','binary_acquisition_exact_bindings'],['runtime_trust','outward_acquisition_exact_bindings'],['replay','atomic_claims'],['non_collection']];for(const path of paths){let source=exact;for(const key of path)source=source[key];const reordered=structuredClone(exact);let at=reordered;for(const key of path.slice(0,-1))at=at[key];at[path.at(-1)]=[...source].reverse();assert.doesNotThrow(()=>assertNormativeHttpContract(reordered),`${path.join('.')} reorder`);for(const [kind,replacement] of [['duplicate',[...source.slice(0,-1),source[0]]],['substitute',[...source.slice(0,-1),'arbitrary_substitution']]]){const mutated=structuredClone(exact);let target=mutated;for(const key of path.slice(0,-1))target=target[key];target[path.at(-1)]=replacement;assert.throws(()=>assertNormativeHttpContract(mutated),/HTTP contract/,`${path.join('.')} ${kind}`);}}});
const canonical=v=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
const resign=e=>({...e,presentation_token:createHmac('sha256',key).update(canonical(Object.fromEntries(Object.entries(e).filter(([name])=>name!=='presentation_token')))).digest('base64url')});
const treeStats=value=>{const stats={nodes:0,bytes:0,maxDepth:0,maxWidth:0,maxArray:0},visit=(node,depth)=>{stats.nodes++;stats.maxDepth=Math.max(stats.maxDepth,depth);if(typeof node==='string')stats.bytes+=Buffer.byteLength(node);else if(Array.isArray(node)){stats.maxArray=Math.max(stats.maxArray,node.length);node.forEach(child=>visit(child,depth+1));}else if(node&&typeof node==='object'){stats.maxWidth=Math.max(stats.maxWidth,Object.keys(node).length);for(const [name,child] of Object.entries(node)){stats.bytes+=Buffer.byteLength(name);visit(child,depth+1);}}};visit(value,0);return stats;};
const utf8Bytes=bytes=>'😀'.repeat(Math.floor(bytes/4))+(bytes%4===3?'界':bytes%4===2?'é':bytes%4===1?'a':'');
test('random nonces differ at the same time; fixture nonce requires literal boolean true',()=>{const {fixture_nonce,synthetic_fixture,...production}=input,a=issuePresentation(production),b=issuePresentation(production);assert.notEqual(a.response_nonce,b.response_nonce);assert.notEqual(a.presentation_token,b.presentation_token);assert.deepEqual(fixtureIssue(),fixtureIssue());for(const marker of [undefined,false,'true','false',0,1,[],{},[true]]){const candidate={...input,synthetic_fixture:marker,fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'};if(marker===undefined)delete candidate.synthetic_fixture;assert.throws(()=>issuePresentation(candidate),/synthetic_fixture:true/,String(marker));}assert.equal(issuePresentation({...input,synthetic_fixture:true,fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'}).response_nonce,'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');assert.equal('response_counter' in a,false);});
test('persistent atomic replay contract is mandatory, scoped, retained through expiry plus skew, and shared replay fails',()=>{const e=fixtureIssue();assert.throws(()=>verify(e),/replay store required/);const shared=store();const v=verify(e,shared);assert.deepEqual(v.scope,{tenant_id:input.tenant_id,key_id:input.key_id});assert.equal(v.retain_until,'2026-08-17T10:02:05.000Z');assert.deepEqual(shared.calls[0].claims.map(x=>x.type),['token','nonce']);assert.throws(()=>verify(e,shared),/replay claim rejected/);assert.throws(()=>verify(e,{claim(){throw Error('down')}}),/failed closed/);});
test('presentation trust, bindings, expiry, and safety byte identity fail closed',()=>{const e=fixtureIssue();assert.deepEqual(canonicalSafetyBytes(e.canonical_record),canonicalSafetyBytes(input.record));assert.equal(verify(e,store()).valid,true);assert.throws(()=>verifyPresentation(e,{trusted_keys:{x:{status:'active',key}},trusted_context:tc,release_revision:input.release_revision,now:input.now,replay_store:store()}),/unknown presentation key/);assert.throws(()=>verifyPresentation(e,{trusted_keys:{[input.key_id]:{status:'revoked',key}},trusted_context:tc,release_revision:input.release_revision,now:input.now,replay_store:store()}),/revoked/);assert.throws(()=>verify({...e,canonical_record:{...e.canonical_record,provider_identity:'tampered'}},store()),/record binding/);assert.throws(()=>verify({...e,presentation_token:`A${e.presentation_token.slice(1)}`},store()),/signature/);assert.throws(()=>verifyPresentation(e,{trusted_keys,trusted_context:{...tc,tenant_id:'other'},release_revision:input.release_revision,now:input.now,replay_store:store()}),/scope binding/);assert.throws(()=>verifyPresentation(e,{trusted_keys,trusted_context:tc,release_revision:input.release_revision,now:e.expires_at,replay_store:store()}),/expired/);});
test('presentation lifetime maximum has an exact inclusive 300-second boundary',()=>{assert.equal(PRESENTATION_MAX_TTL_SECONDS,300);const exact=issuePresentation({...input,ttl_seconds:PRESENTATION_MAX_TTL_SECONDS,fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'});assert.equal(exact.expires_at,'2026-08-17T10:05:00.000Z');assert.equal(verify(exact,store()).valid,true);assert.throws(()=>issuePresentation({...input,ttl_seconds:PRESENTATION_MAX_TTL_SECONDS+1}),/ttl_seconds invalid integer/);});
test('multilingual safety strings use bounded UTF-8 bytes, including combining and astral text',()=>{const withText=value=>({...input.record,provider_identity:value});for(const value of ['界'.repeat(53)+'a',('e\u0301').repeat(53)+'a','😀'.repeat(40)]){assert.equal(Buffer.byteLength(value),160);assert.doesNotThrow(()=>canonicalSafetyBytes(withText(value)));}for(const value of ['界'.repeat(54),('e\u0301').repeat(53)+'é','😀'.repeat(40)+'a']){assert.ok(Buffer.byteLength(value)>160);assert.throws(()=>canonicalSafetyBytes(withText(value)),/invalid text/);}const at64='😀'.repeat(16),above64=at64+'a';assert.equal(Buffer.byteLength(at64),64);assert.doesNotThrow(()=>issuePresentation({...input,trusted_context:{...tc,app_version:at64}}));assert.throws(()=>issuePresentation({...input,trusted_context:{...tc,app_version:above64}}),/app_version invalid text/);});
test('every safety-field array is dense, own-indexed, bounded, and revision-safe',()=>{const arrayFields=SAFETY_FIELDS.slice(0,4),recordWith=(field,value)=>({...input.record,[field]:value});for(const field of arrayFields){const rejects=[];const first=[,'b'],middle=['a',,'c'],last=['a','b'];last.length=3;const allocated=new Array(1),deleted=['a','b'];delete deleted[1];const inherited=new Array(1),prototype={0:'inherited'};Object.setPrototypeOf(inherited,prototype);rejects.push(first,middle,last,allocated,deleted,inherited,[undefined],[null]);for(const value of rejects)assert.throws(()=>canonicalSafetyBytes(recordWith(field,value)),new RegExp(`canonical_record\\.${field} invalid array`),`${field} accepted ${String(value)}`);for(const dense of [[],['a'],['a','b']])assert.doesNotThrow(()=>canonicalSafetyBytes(recordWith(field,dense)),`${field} rejected dense array`);const one=deriveRecordRevision(recordWith(field,['a'])),two=deriveRecordRevision(recordWith(field,['a','b']));assert.notEqual(one,two,`${field} dense canonical revisions collided`);}});
test('completed signed envelope enforces exact recursive boundaries including wrapper overhead',()=>{const fields=['callable_numbers','sms_codes','contact_urls','contact_emails'],lengths=[100,100,29,1],record={...input.record};for(const [index,field] of fields.entries())record[field]=Array(lengths[index]).fill('a');const exactNodes=issuePresentation({...input,record});assert.deepEqual(treeStats(exactNodes),{nodes:256,bytes:1089,maxDepth:3,maxWidth:13,maxArray:100});assert.throws(()=>issuePresentation({...input,record:{...record,contact_emails:['a','a']}}),/envelope too many nodes/);assert.doesNotThrow(()=>issuePresentation({...input,record:{...input.record,callable_numbers:Array(100).fill('a')}}));assert.throws(()=>issuePresentation({...input,record:{...input.record,callable_numbers:Array(101).fill('a')}}),/invalid array|oversized array/);const width=value=>{const e={...fixtureIssue()};for(let index=0;index<value-13;index++)e[`extra_${index}`]='a';return e;};assert.equal(Object.keys(width(32)).length,32);assert.throws(()=>verify(width(32),store()),/unknown field/);assert.throws(()=>verify(width(33),store()),/object too wide/);const depth5={...fixtureIssue(),canonical_record:{...input.record,callable_numbers:[[['a']]]}},depth6={...fixtureIssue(),canonical_record:{...input.record,callable_numbers:[[[['a']]]]}};assert.equal(treeStats(depth5).maxDepth,5);assert.throws(()=>verify(depth5,store()),/invalid array/);assert.throws(()=>verify(depth6,store()),/nesting too deep/);});
test('completed envelope aggregate UTF-8 limit includes metadata and token wrapper overhead',()=>{const fields=['callable_numbers','sms_codes','contact_urls','contact_emails'],lengths=[100,100,29,1],record={...input.record};let remaining=31909,used=0;for(const [fieldIndex,field] of fields.entries()){record[field]=Array.from({length:lengths[fieldIndex]},()=>{const bytes=Math.min(160,remaining-(230-used-1));remaining-=bytes;used++;return utf8Bytes(bytes);});}assert.equal(remaining,0);const exact=issuePresentation({...input,record});assert.equal(treeStats(exact).bytes,32768);const above={...record,contact_emails:[`${record.contact_emails[0]}a`]};assert.throws(()=>issuePresentation({...input,record:above}),/envelope aggregate bytes exceeded/);});
test('release revision has signed alternate-issuer UTF-8 boundary and verifier parity',()=>{for(const release_revision of ['界'.repeat(53)+'a','😀'.repeat(40)]){assert.equal(Buffer.byteLength(release_revision),160);const e=issuePresentation({...input,release_revision});assert.equal(verifyPresentation(e,{trusted_keys,trusted_context:tc,release_revision,now:'2026-08-17T10:01:00.000Z',replay_store:store()}).valid,true);}const over='😀'.repeat(40)+'a',signed=resign({...fixtureIssue(),release_revision:over});assert.equal(Buffer.byteLength(over),161);assert.throws(()=>verifyPresentation(signed,{trusted_keys,trusted_context:tc,release_revision:over,now:'2026-08-17T10:01:00.000Z',replay_store:store()}),/release_revision invalid text/);assert.throws(()=>issuePresentation({...input,release_revision:over}),/release_revision invalid text/);});
test('presentation MAC precedes derived metadata comparison and replay claim',()=>{const e=fixtureIssue(),replay=store(),tampered={...e,presentation_metadata:{...e.presentation_metadata,opaque_alias:`A${e.presentation_metadata.opaque_alias.slice(1)}`}};assert.throws(()=>verify(tampered,replay),/invalid signature/);assert.equal(replay.calls.length,0);});
test('opaque metadata and digests are app/version scoped without changing safety bytes',()=>{const a=fixtureIssue(),forApp=app_id=>issuePresentation({...input,trusted_context:{...tc,app_id},fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'}),forVersion=app_version=>issuePresentation({...input,trusted_context:{...tc,app_version},fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'}),b=forApp('app-synthetic-b'),v=forVersion('synthetic-2.0');for(const other of [b,v]){assert.notEqual(a.presentation_metadata.opaque_alias,other.presentation_metadata.opaque_alias);assert.notEqual(a.presentation_metadata.opaque_canary,other.presentation_metadata.opaque_canary);assert.notEqual(sha256(Buffer.from(a.presentation_metadata.opaque_alias)),sha256(Buffer.from(other.presentation_metadata.opaque_alias)));assert.notEqual(sha256(Buffer.from(a.presentation_metadata.opaque_canary)),sha256(Buffer.from(other.presentation_metadata.opaque_canary)));assert.deepEqual(canonicalSafetyBytes(a.canonical_record),canonicalSafetyBytes(other.canonical_record));assert.equal(a.record_revision,other.record_revision);}});
function sign(kind,body){const e=fixtureIssue(),bound=['render','presentation'].includes(kind)?{record_revision:recordRevision,presentation_status:'active',presentation_issued_at:e.issued_at,presentation_expires_at:e.expires_at,issuance_key_id:e.key_id}:{};return signSyntheticEvidence(kind,{...bound,...body},{synthetic_fixture:true,evidence_key_id:'obs-key-1',evidence_key:obsKey});}
const base={observation_id:'obs-1',tenant_id:input.tenant_id,app_id:'app-synthetic-a',app_version:'synthetic-1.0'};
const ctx=e=>({observation_keys,registered_apps,presentation_ledger:ledgerFor(e),metadata_registry,presentation_keys,acquisition_registry,scan_version_registry});
test('all evidence is signed, domain separated, app registered, and presentation-ledger bound',()=>{const e=fixtureIssue(),c=ctx(e),pd=sha256(Buffer.from(e.presentation_token));const render=sign('render',{...base,presentation_token_digest:pd,record_revision:recordRevision,coarse_time_bucket:'2026-08-17T10:00:00.000Z',render_count:2});assert.equal(validateRenderAttestation(render,c).tenant_id,input.tenant_id);assert.throws(()=>validateRenderAttestation({...render,render_count:3},c),/signature/);assert.throws(()=>validateFetchObservation(render,c),/unknown field|domain/);assert.throws(()=>validateRenderAttestation(render,{...c,observation_keys:{'obs-key-1':{status:'revoked',key:obsKey}}}),/revoked/);assert.throws(()=>validateRenderAttestation(render,{...c,registered_apps:{}}),/registry invalid|unknown/);assert.throws(()=>validateRenderAttestation(render,{...c,presentation_ledger:{[pd]:{...ledgerFor(e)[pd],app_id:'other'}}}),/binding mismatch/);});
test('presentation ledger binds every issuance field, validity interval, and active issuance key',()=>{const e=fixtureIssue(),c=ctx(e),pd=sha256(Buffer.from(e.presentation_token)),body={...base,presentation_token_digest:pd,surface_class:'licensed_app',observed_at:'2026-08-17T10:01:00.000Z'};assert.equal(validatePresentationObservation(sign('presentation',body),c).issuance_key_id,input.key_id);for(const field of ['tenant_id','app_id','app_version','record_revision','issued_at','expires_at','key_id']){const entry={...ledgerFor(e)[pd],[field]:field.endsWith('_at')?'2026-08-17T09:00:00.000Z':'substituted'};assert.throws(()=>validatePresentationObservation(sign('presentation',body),{...c,presentation_ledger:{[pd]:entry}}));}assert.throws(()=>validatePresentationObservation(sign('presentation',{...body,observed_at:'2026-08-17T09:59:59.000Z'}),c),/before issuance/);assert.throws(()=>validatePresentationObservation(sign('presentation',{...body,observed_at:e.expires_at}),c),/at or after expiry/);assert.throws(()=>validatePresentationObservation(sign('presentation',body),{...c,presentation_keys:{[input.key_id]:{status:'revoked',key}}}),/revoked/);});
test('ledger-backed presentation and render evidence enforce canonical bounded lifetimes',()=>{const e=fixtureIssue(),pd=sha256(Buffer.from(e.presentation_token)),original=ledgerFor(e)[pd];const validateLedger=(entry,{observed_at='2026-08-17T10:04:59.000Z',coarse_time_bucket='2026-08-17T10:00:00.000Z'}={})=>{const c={...ctx(e),presentation_ledger:{[pd]:entry}},bound={...base,presentation_token_digest:pd,presentation_issued_at:entry.issued_at,presentation_expires_at:entry.expires_at};const presentation=sign('presentation',{...bound,surface_class:'licensed_app',observed_at}),render=sign('render',{...bound,record_revision:recordRevision,coarse_time_bucket,render_count:1});return{presentation:()=>validatePresentationObservation(presentation,c),render:()=>validateRenderAttestation(render,c)};};const exact={...original,issued_at:'2026-08-17T10:00:00.000Z',expires_at:'2026-08-17T10:05:00.000Z'};for(const validate of Object.values(validateLedger(exact)))assert.doesNotThrow(validate);const invalid=[['alternate 300.001-second ledger',{...exact,expires_at:'2026-08-17T10:05:00.001Z'}],['alternate 301-second ledger',{...exact,expires_at:'2026-08-17T10:05:01.000Z'}],['stale overlong ledger',{...exact,issued_at:'2026-08-16T10:00:00.000Z',expires_at:'2026-08-16T10:05:01.000Z'}],['equal timestamps',{...exact,expires_at:exact.issued_at}],['reversed timestamps',{...exact,issued_at:'2026-08-17T10:05:00.000Z',expires_at:'2026-08-17T10:00:00.000Z'}],['normalizing timestamp',{...exact,issued_at:'2026-08-17T10:00:00Z'}],['calendar-rollover timestamp',{...exact,issued_at:'2026-02-30T10:00:00.000Z'}],['leap-second timestamp',{...exact,issued_at:'2026-08-17T09:59:60.000Z'}]];for(const [label,entry] of invalid)for(const [kind,validate] of Object.entries(validateLedger(entry)))assert.throws(validate,/invalid (?:timestamp|lifetime)/,`${label} accepted for ${kind}`);});
test('runtime rejects leap seconds in every schema-backed timestamp role',()=>{const leap='2026-08-17T10:00:60.000Z',e=fixtureIssue(),c=ctx(e),pd=sha256(Buffer.from(e.presentation_token));assert.throws(()=>issuePresentation({...input,now:leap}),/invalid now/);for(const field of ['issued_at','expires_at'])assert.throws(()=>verify(resign({...e,[field]:leap}),store()),/invalid timestamp/,field);const body={...base,presentation_token_digest:pd,surface_class:'licensed_app',observed_at:'2026-08-17T10:01:00.000Z'};for(const field of ['presentation_issued_at','presentation_expires_at','observed_at'])assert.throws(()=>validatePresentationObservation(sign('presentation',{...body,[field]:leap}),c),/invalid timestamp/,field);const render={...base,presentation_token_digest:pd,record_revision:recordRevision,coarse_time_bucket:'2026-08-17T10:00:00.000Z',render_count:1};for(const field of ['presentation_issued_at','presentation_expires_at'])assert.throws(()=>validateRenderAttestation(sign('render',{...render,[field]:leap}),c),/invalid timestamp/,field);});
test('schema enums are enforced at runtime and signed free-form values fail',()=>{const e=fixtureIssue(),c=ctx(e),pd=sha256(Buffer.from(e.presentation_token));assert.throws(()=>validatePresentationObservation(sign('presentation',{...base,presentation_token_digest:pd,surface_class:'covert-channel',observed_at:'2026-08-17T10:01:00.000Z'}),c),/surface_class invalid enum/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,surface_class:'signed-free-form'}),c),/surface_class invalid enum/);assert.throws(()=>validateBinaryObservation(sign('binary',{...base,observation_id:'b-enum',artifact_sha256:artifactDigest,platform:'browser',acquisition_provenance:'registered_capture_service',acquisition_id:'synthetic-build-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:null}),c),/platform invalid enum/);});
test('closed fields and strict resource caps run before signature canonicalization',()=>{const e=fixtureIssue(),c=ctx(e),normal=sign('fetch',{...base,coarse_time_bucket:'2026-08-17T10:00:00.000Z',fetch_count:1,unique_token_count:1,conditional_request_count:0,surface_count:1});assert.throws(()=>validateFetchObservation({...normal,unknown:'x'.repeat(50000)},c),/unknown field/);const wide={...normal};for(let i=0;i<40;i++)wide[`x${i}`]=i;assert.throws(()=>validateFetchObservation(wide,c),/object too wide|unknown field/);assert.throws(()=>validateFetchObservation({...normal,app_version:'x'.repeat(40000)},c),/aggregate bytes exceeded/);const deep={...normal,extra:{a:{b:{c:{d:{e:1}}}}}};assert.throws(()=>validateFetchObservation(deep,c),/unknown field/);});
const outwardBody={observation_id:'out-1',artifact_sha256:artifactDigest,acquisition_provenance:'registered_capture_service',acquisition_id:'build-synthetic-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest,surface_class:'third_party_app',coarse_time_bucket:'2026-08-17T10:00:00.000Z',match_count:1};
test('outward match count and metadata digest have an exact positive-or-neutral invariant',()=>{const c=ctx(fixtureIssue());assert.equal(validateOutwardObservation(sign('outward',outwardBody),c).match_count,1);assert.equal(validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-neutral',matched_metadata_digest:null,match_count:0}),c).registry_match,false);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-positive-null',matched_metadata_digest:null,match_count:1}),c),/count and metadata digest mismatch/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-zero-digest',match_count:0}),c),/count and metadata digest mismatch/);});
test('outward capture attribution requires registered artifact provenance; authenticated non-match is neutral',()=>{const e=fixtureIssue(),c=ctx(e),v=validateOutwardObservation(sign('outward',outwardBody),c);assert.equal(v.tenant_id,input.tenant_id);assert.equal(v.metadata_type,'canary');const none=validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-none',matched_metadata_digest:null,match_count:0}),c);assert.equal(none.registry_match,false);assert.equal(analyzeCompliance({outward:[none]}).signals[0].code,'insufficient_evidence');assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,artifact_sha256:sha256(Buffer.from('tamper'))}),c),/acquisition registry binding/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,matched_metadata_digest:sha256(Buffer.from('unknown'))}),c),/unknown issued metadata/);assert.throws(()=>validateOutwardObservation(sign('outward',outwardBody),{...c,metadata_registry:{[metadataDigest]:{...metadata_registry[metadataDigest],status:'revoked'}}}),/revoked/);});
test('outward alias and canary provenance stay registry-derived, frozen, and type-specific in analysis',()=>{const e=fixtureIssue(),aliasDigest=sha256(Buffer.from(e.presentation_metadata.opaque_alias)),aliasEntry={...metadata_registry[metadataDigest],metadata_type:'alias'},c={...ctx(e),metadata_registry:{...metadata_registry,[aliasDigest]:aliasEntry}},alias=validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-alias',matched_metadata_digest:aliasDigest}),c),canary=validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-canary'}),c);assert.equal(alias.metadata_type,'alias');assert.equal(canary.metadata_type,'canary');assert.equal(Object.isFrozen(alias),true);assert.throws(()=>{alias.metadata_type='canary';},TypeError);const aliasCodes=analyzeCompliance({outward:[alias]}).signals.map(signal=>signal.code);assert.deepEqual(aliasCodes,['outward_in_alias_match']);assert.equal(aliasCodes.includes('outward_in_canary_match'),false);assert.deepEqual(analyzeCompliance({outward:[canary]}).signals.map(signal=>signal.code),['outward_in_canary_match']);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'observer-type',metadata_type:'canary',matched_metadata_digest:aliasDigest}),c),/unknown field/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'tampered-type',matched_metadata_digest:aliasDigest}),{...c,metadata_registry:{[aliasDigest]:{...aliasEntry,metadata_type:'canary'}}}),/derivation mismatch/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'revoked-alias',matched_metadata_digest:aliasDigest}),{...c,metadata_registry:{[aliasDigest]:{...aliasEntry,status:'revoked'}}}),/revoked/);});
test('metadata registry proves derivation before outward attribution or binary acceptance',()=>{const e=fixtureIssue(),c=ctx(e),otherApp='app-synthetic-b',otherVersion='synthetic-2.0',apps={...registered_apps,[`${input.tenant_id}\0${otherApp}\0synthetic-1.0`]:{status:'active'},[`${input.tenant_id}\0app-synthetic-a\0${otherVersion}`]:{status:'active'}};for(const patch of [{app_id:otherApp},{app_version:otherVersion}]){const poisoned={...metadata_registry[metadataDigest],...patch},bad={...c,registered_apps:apps,metadata_registry:{[metadataDigest]:poisoned}};assert.throws(()=>validateOutwardObservation(sign('outward',outwardBody),bad),/derivation mismatch/);const binary={...base,observation_id:`bin-cross-${patch.app_id||patch.app_version}`,artifact_sha256:artifactDigest,platform:'ios',acquisition_provenance:'registered_capture_service',acquisition_id:'synthetic-build-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest};assert.throws(()=>validateBinaryObservation(sign('binary',binary),bad),/derivation mismatch/);}const other=issuePresentation({...input,trusted_context:{...tc,app_id:otherApp},fixture_nonce:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'}),otherDigest=sha256(Buffer.from(other.presentation_metadata.opaque_canary)),registry={...metadata_registry,[otherDigest]:{...metadata_registry[metadataDigest],app_id:otherApp}},otherContext={...c,registered_apps:apps,metadata_registry:registry};const outward=validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-other',matched_metadata_digest:otherDigest}),otherContext);assert.equal(outward.app_id,otherApp);const cross={...base,observation_id:'bin-cross-valid',artifact_sha256:artifactDigest,platform:'ios',acquisition_provenance:'registered_capture_service',acquisition_id:'synthetic-build-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:otherDigest};assert.throws(()=>validateBinaryObservation(sign('binary',cross),otherContext),/app binding mismatch/);const correctlyScoped=sign('binary',{...cross,observation_id:'bin-other-valid',app_id:otherApp}),scopedContext={...otherContext,acquisition_registry:{...acquisition_registry,'other-build':{...binaryAcquisition,app_id:otherApp}}};correctlyScoped.acquisition_id='other-build';assert.throws(()=>validateBinaryObservation(correctlyScoped,scopedContext),/signature/);const resigned=sign('binary',{...cross,observation_id:'bin-other-valid',app_id:otherApp,acquisition_id:'other-build'});assert.equal(validateBinaryObservation(resigned,scopedContext).registry_match,true);});
test('privacy-safe binary observation supports match/non-match and rejects tamper/mismatch',()=>{const e=fixtureIssue(),c=ctx(e);const body={...base,observation_id:'bin-1',artifact_sha256:artifactDigest,platform:'ios',acquisition_provenance:'registered_capture_service',acquisition_id:'synthetic-build-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest};const match=validateBinaryObservation(sign('binary',body),c);assert.equal(match.matched_metadata_digest,metadataDigest);const none=validateBinaryObservation(sign('binary',{...body,observation_id:'bin-2',matched_metadata_digest:null}),c);assert.equal(none.registry_match,false);assert.throws(()=>validateBinaryObservation({...sign('binary',body),platform:'android'},c),/signature/);assert.throws(()=>validateBinaryObservation(sign('binary',{...body,app_id:'other'}),c),/registered app/);assert.equal(JSON.stringify(body).includes('callable_numbers'),false);});
test('binary acquisition registry closes every ownership, platform, artifact, id, status, and field substitution',()=>{const e=fixtureIssue(),body={...base,observation_id:'bin-bound',artifact_sha256:artifactDigest,platform:'ios',acquisition_provenance:'registered_capture_service',acquisition_id:'synthetic-build-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest},apps={...registered_apps,'tenant-other\0app-synthetic-a\0synthetic-1.0':{status:'active'},'tenant-synthetic-a\0app-other\0synthetic-1.0':{status:'active'},'tenant-synthetic-a\0app-synthetic-a\0synthetic-2.0':{status:'active'}},c={...ctx(e),registered_apps:apps};assert.equal(validateBinaryObservation(sign('binary',body),c).registry_match,true,'exact acquisition binding must pass');for(const [field,value] of [['tenant_id','tenant-other'],['app_id','app-other'],['app_version','synthetic-2.0'],['platform','android'],['artifact_sha256',sha256(Buffer.from('other artifact'))]])assert.throws(()=>validateBinaryObservation(sign('binary',{...body,observation_id:`bin-cross-${field}`,[field]:value}),c),/acquisition .*binding mismatch/,field);assert.throws(()=>validateBinaryObservation(sign('binary',{...body,observation_id:'bin-cross-acquisition',acquisition_id:'build-synthetic-1'}),c),/acquisition entry missing|acquisition registry binding mismatch/);assert.throws(()=>validateBinaryObservation(sign('binary',{...body,observation_id:'bin-revoked'}),{...c,acquisition_registry:{...acquisition_registry,'synthetic-build-1':{...binaryAcquisition,status:'revoked'}}}),/acquisition registry binding mismatch/);for(const field of ['status','evidence_type','tenant_id','app_id','app_version','platform','artifact_sha256','acquisition_provenance','scan_method','scan_version']){const entry={...binaryAcquisition};delete entry[field];assert.throws(()=>validateBinaryObservation(sign('binary',{...body,observation_id:`bin-missing-${field}`}),{...c,acquisition_registry:{...acquisition_registry,'synthetic-build-1':entry}}),new RegExp(`acquisition entry missing ${field}`),field);}});
test('only exactly acquisition-bound binary evidence contributes the analysis signal',()=>{const e=fixtureIssue(),c=ctx(e),body={...base,observation_id:'bin-signal-bound',artifact_sha256:artifactDigest,platform:'ios',acquisition_provenance:'registered_capture_service',acquisition_id:'synthetic-build-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest},verified=validateBinaryObservation(sign('binary',body),c);assert.deepEqual(analyzeCompliance({binaries:[verified]}).signals.map(x=>x.code),['app_binary_metadata_match']);assert.throws(()=>validateBinaryObservation(sign('binary',{...body,observation_id:'bin-signal-cross',platform:'android'}),{...c,registered_apps}),/binding mismatch/);assert.throws(()=>analyzeCompliance({binaries:[{...verified,platform:'android'}]}),/exact verified/);});
function vf(hour,count,idSuffix='x'){return validateFetchObservation(sign('fetch',{...base,observation_id:`f-${hour.slice(11,13)}-${idSuffix}`,coarse_time_bucket:hour,fetch_count:count,unique_token_count:Math.min(count,1),conditional_request_count:0,surface_count:1}),ctx(fixtureIssue()));}
test('calendar hours require canonical UTC round-trip equality',()=>{assert.equal(vf('2024-02-29T10:00:00.000Z',1,'leap').coarse_time_bucket,'2024-02-29T10:00:00.000Z');assert.equal(vf('2026-02-28T10:00:00.000Z',1,'valid').coarse_time_bucket,'2026-02-28T10:00:00.000Z');for(const value of ['2026-02-30T10:00:00.000Z','2025-02-29T10:00:00.000Z'])assert.throws(()=>vf(value,1,'invalid'),/valid UTC hour/);const c=ctx(fixtureIssue());assert.throws(()=>validateRenderAttestation(sign('render',{...base,presentation_token_digest:sha256(Buffer.from(fixtureIssue().presentation_token)),coarse_time_bucket:'2026-02-30T10:00:00.000Z',render_count:1}),c),/valid UTC hour/);assert.throws(()=>validateOutwardObservation(sign('outward',{...outwardBody,coarse_time_bucket:'2026-02-30T10:00:00.000Z'}),c),/valid UTC hour/);});
test('analysis requires exact deeply-frozen verified identity and rejects spread, clone, and modification',()=>{const v=vf('2026-08-17T10:00:00.000Z',1);assert.ok(Object.isFrozen(v));assert.throws(()=>{v.nested={};},TypeError);for(const x of [{...v},structuredClone(v),{...v,fetch_count:999}])assert.throws(()=>analyzeCompliance({fetches:[x]}),/exact verified/);});
function analysisEvidence(){const e=fixtureIssue(),c=ctx(e),pd=sha256(Buffer.from(e.presentation_token));return{presentations:validatePresentationObservation(sign('presentation',{...base,observation_id:'analysis-presentation',presentation_token_digest:pd,surface_class:'licensed_app',observed_at:'2026-08-17T10:01:00.000Z'}),c),renders:validateRenderAttestation(sign('render',{...base,observation_id:'analysis-render',presentation_token_digest:pd,record_revision:recordRevision,coarse_time_bucket:'2026-08-17T10:00:00.000Z',render_count:2}),c),fetches:validateFetchObservation(sign('fetch',{...base,observation_id:'analysis-fetch',coarse_time_bucket:'2026-08-17T10:00:00.000Z',fetch_count:100,unique_token_count:100,conditional_request_count:1,surface_count:1}),c),outward:validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'analysis-outward'}),c),binaries:validateBinaryObservation(sign('binary',{...base,observation_id:'analysis-binary',artifact_sha256:artifactDigest,platform:'ios',acquisition_provenance:'registered_capture_service',acquisition_id:'synthetic-build-1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest}),c)};}
test('analysis rejects every pairwise wrong-bucket placement before deriving signals',()=>{const evidence=analysisEvidence(),buckets=Object.keys(evidence);for(const source of buckets)for(const target of buckets)if(source!==target)assert.throws(()=>analyzeCompliance({[target]:[evidence[source]]}),new RegExp(`${target} requires`),`${source} accepted in ${target}`);});
test('analysis fails closed for mixed arrays, duplicate ids, unknown buckets, mutated sources, and lookalikes',()=>{const evidence=analysisEvidence();assert.throws(()=>analyzeCompliance({fetches:[evidence.fetches,evidence.renders]}),/fetches requires fetch evidence/);assert.throws(()=>analyzeCompliance({fetches:[evidence.fetches],renders:[evidence.fetches]}),/renders requires render evidence/);assert.throws(()=>analyzeCompliance({fetches:[evidence.fetches,evidence.fetches]}),/duplicate observation_id/);assert.throws(()=>analyzeCompliance({fetches:[evidence.fetches],mystery:[]}),/unknown bucket/);assert.throws(()=>analyzeCompliance({fetches:[{...evidence.fetches}]}),/exact verified/);const signed=sign('fetch',{...base,observation_id:'mutated-source',coarse_time_bucket:'2026-08-17T10:00:00.000Z',fetch_count:1,unique_token_count:1,conditional_request_count:0,surface_count:1}),verified=validateFetchObservation(signed,ctx(fixtureIssue()));signed.evidence_type='render';assert.throws(()=>analyzeCompliance({fetches:[signed]}),/exact verified/);assert.equal(verified.evidence_type,'fetch');assert.throws(()=>{verified.evidence_type='render';},TypeError);});
test('correctly bucketed verified evidence preserves existing analysis signals',()=>{const evidence=analysisEvidence(),result=analyzeCompliance(Object.fromEntries(Object.entries(evidence).map(([bucket,observation])=>[bucket,[observation]]))),codes=new Set(result.signals.map(signal=>signal.code));for(const code of ['bounded_render_fetch_ratio','bulk_sweep','conditional_requests_despite_no_store','outward_in_canary_match','app_binary_metadata_match'])assert.ok(codes.has(code),`missing ${code}`);assert.equal(result.assessment,'corroborating_only_not_conclusive');});
test('flat volume aggregates distinct hours and requires equal positive consecutive run',()=>{const h=n=>`2026-08-17T${String(n).padStart(2,'0')}:00:00.000Z`,flat=a=>analyzeCompliance({fetches:a}).signals.some(s=>s.code==='flat_volume_pattern');assert.equal(flat([vf(h(10),1,'a'),vf(h(10),1,'b'),vf(h(10),1,'c')]),false,'duplicates are one bucket');assert.equal(flat([vf(h(10),2),vf(h(12),2),vf(h(13),2)]),false,'gap');assert.equal(flat([vf(h(10),2),vf(h(11),3),vf(h(12),2)]),false,'non-equal');assert.equal(flat([vf(h(10),2),vf(h(11),2),vf(h(12),2)]),true,'valid run');assert.equal(flat([vf(h(10),1,'a'),vf(h(10),1,'b'),vf(h(11),2),vf(h(12),2)]),true,'same-hour aggregation');});
test('app versions are incomparable in ratios and flat-volume series',()=>{const h=n=>`2026-08-17T${String(n).padStart(2,'0')}:00:00.000Z`,otherRegistry={...registered_apps,'tenant-synthetic-a\0app-synthetic-a\0synthetic-2.0':{status:'active'}},make=(n,version)=>validateFetchObservation(sign('fetch',{...base,app_version:version,observation_id:`cv-${n}-${version}`,coarse_time_bucket:h(n),fetch_count:2,unique_token_count:1,conditional_request_count:0,surface_count:1}),{...ctx(fixtureIssue()),registered_apps:otherRegistry});const r=analyzeCompliance({fetches:[make(10,'synthetic-1.0'),make(11,'synthetic-2.0'),make(12,'synthetic-1.0')]});assert.equal(r.signals.some(x=>x.code==='flat_volume_pattern'),false);assert.ok(r.signals.filter(x=>x.code==='missing_render_attestation').every(x=>x.detail.app_version));});
test('corroborating evidence remains non-conclusive',()=>{const e=fixtureIssue(),c=ctx(e);const out=validateOutwardObservation(sign('outward',{...outwardBody,observation_id:'out-z',surface_class:'public_web'}),c);const bin=validateBinaryObservation(sign('binary',{...base,observation_id:'bin-z',artifact_sha256:sha256(Buffer.from('a')),platform:'ios',acquisition_provenance:'licensed_store_artifact',acquisition_id:'a1',scan_method:'static_digest_scan_v1',scan_version:'1',matched_metadata_digest:metadataDigest}),c);const r=analyzeCompliance({outward:[out],binaries:[bin]});assert.ok(r.signals.every(s=>s.conclusive===false));assert.equal(r.assessment,'corroborating_only_not_conclusive');});
test('nonpublication rejects marker-stripped licensed semantic subtree and counsel excerpt',()=>{const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-nonpub-')),dist=resolve(root,'dist');mkdirSync(dist);try{const http=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/http-contract.json')));writeFileSync(resolve(dist,'subtree.json'),JSON.stringify(http.replay));assert.throws(()=>assertInternalNonpublication(dist,repo),/semantic section|scalar fingerprint/);rmSync(dist,{recursive:true});mkdirSync(dist);const terms=readFileSync(resolve(repo,'reviews/licensed-delivery/v1/terms.counsel-draft.md'),'utf8'),excerpt=terms.split(/\n\s*\n/).find(x=>x.includes('Replay prevention requires'));writeFileSync(resolve(dist,'draft.txt'),excerpt.replace(/\s+/g,' ').trim());assert.throws(()=>assertInternalNonpublication(dist,repo),/scalar fingerprint/);}finally{rmSync(root,{recursive:true,force:true});}});
test('nonpublication rejects normalized licensed schema and HTTP contract scalars',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-contract-nonpub-'));
  const schema='Internal licensed-delivery v1 closed schema bundle',http='future_authenticated_runtime_contract_not_active';
  const percent=value=>[...Buffer.from(value)].map(byte=>`%${byte.toString(16).padStart(2,'0')}`).join('');
  const entities=value=>[...value].map(character=>`&#${character.codePointAt(0)};`).join('');
  const js=value=>[...value].map(character=>`\\u${character.codePointAt(0).toString(16).padStart(4,'0')}`).join('');
  const split=value=>{const at=Math.floor(value.length/2);return `${value.slice(0,at)}<span></span>${value.slice(at)}`;};
  const cases=[
    ['schema-raw.txt',schema],
    ['http-extracted.json',JSON.stringify({public:true,value:http},null,3)],
    ['schema-entity.txt',entities(schema)],
    ['http-percent.txt',percent(http)],
    ['schema-js.txt',js(schema)],
    ['schema-nested.txt','internal\\u0026#45;licensed'+entities(' delivery v1 closed schema bundle')],
    ['schema-text.html',`<main>${schema}</main>`],
    ['http-split.html',`<p>${split(http)}</p>`],
    ['schema-attribute.html',`<meta content="${entities(percent(schema))}">`],
    ['http-attribute.htm',`<div data-contract='${js(http)}'></div>`],
  ];
  try{
    for(const [name,content] of cases){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.throws(()=>assertInternalNonpublication(dist,repo),/licensed-delivery contract scalar fingerprint/,name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('nonpublication semantically rejects every licensed synthetic fixture and substantive branch',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),fixturesRoot=resolve(repo,'reviews/licensed-delivery/v1/fixtures'),root=mkdtempSync(resolve(tmpdir(),'licensed-fixture-nonpub-'));
  const fixtures=['synthetic-input.json','presentation.synthetic.json','observations.synthetic.json'].map(name=>[name,JSON.parse(readFileSync(resolve(fixturesRoot,name),'utf8'))]);
  const reordered=value=>Array.isArray(value)?value.map(reordered):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).reverse().map(([key,child])=>[key,reordered(child)])):value;
  const assertRejected=(label,value,pattern=/semantic section|scalar fingerprint/)=>{const dist=resolve(root,label.replace(/[^a-z0-9]+/giu,'-'));mkdirSync(dist);writeFileSync(resolve(dist,'transformed.json'),JSON.stringify(reordered(value),null,3));assert.throws(()=>assertInternalNonpublication(dist,repo),pattern,label);};
  try{
    for(const [name,fixture] of fixtures){
      assertRejected(`${name}-whole`,fixture,/internal (?:review-pack marker|evidence exact copy|review-pack semantic section|review-pack scalar fingerprint|licensed-delivery (?:contract|fixture) scalar fingerprint)/);
      const stripped=structuredClone(fixture);delete stripped.synthetic_fixture;if('key'in stripped)stripped.key='ordinary-public-placeholder';assertRejected(`${name}-marker-stripped`,stripped);
      for(const [branch,value] of Object.entries(fixture))if(value&&typeof value==='object')assertRejected(`${name}-${branch}`,value);
    }
    for(const [index,value] of [{status:'active',items:[{label:'Public directory entry',count:2}]},{evidence_type:'public-feedback',platform:'web',message:'Ordinary public JSON.'}].entries()){
      const dist=resolve(root,`control-${index}`);mkdirSync(dist);writeFileSync(resolve(dist,'public.json'),JSON.stringify(value,null,2));assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo));
    }
    const textDist=resolve(root,'text-control');mkdirSync(textDist);writeFileSync(resolve(textDist,'public.txt'),'Public hotline directory information and application help.');assert.doesNotThrow(()=>assertInternalNonpublication(textDist,repo));
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('nonpublication rejects rendered, encoded, and normalized counsel-draft paragraphs without matching common fragments',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-draft-nonpub-'));
  const terms=readFileSync(resolve(repo,'reviews/licensed-delivery/v1/terms.counsel-draft.md'),'utf8');
  const excerpt=terms.split(/\n\s*\n/).find(x=>x.includes('Responses and presentation tokens')).replace(/\s+/g,' ').trim();
  const rejects=[
    ['rendered.html',excerpt.replace(/`([^`]+)`/gu,'<code>$1</code>')],
    ['entities.txt',[...excerpt].map(character=>`&#x${character.codePointAt(0).toString(16)};`).join('')],
    ['split.html',excerpt.toUpperCase().replace('PRESENTATION TOKENS','PRESENTATION <em>TOK</em>ENS')],
  ];
  try{
    for(const [name,content] of rejects){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.throws(()=>assertInternalNonpublication(dist,repo),/scalar fingerprint/,name);}
    for(const [index,content] of ['Authorized application content for a public visitor.','A presentation token may be used by an application.','private no-store max-age 0'].entries()){const dist=resolve(root,`control-${index}`);mkdirSync(dist);writeFileSync(resolve(dist,'public.html'),content);assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo),content);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('nonpublication rejects normalized non-JSON leaks from every licensed fixture evidence branch',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-fixture-rendered-nonpub-'));
  const presentation=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/presentation.synthetic.json')));
  const observations=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/observations.synthetic.json')));
  const percent=value=>[...Buffer.from(value)].map(byte=>`%${byte.toString(16).padStart(2,'0')}`).join('');
  const entities=value=>[...value].map(character=>`&#x${character.codePointAt(0).toString(16)};`).join('');
  const split=value=>{const at=Math.floor(value.length/2);return `${value.slice(0,at)}<span></span>${value.slice(at)}`;};
  const cases=[
    ['outward.html',`<article>${split(observations.outward_observation.evidence_signature)}</article>`],
    ['app-binary.txt',percent(observations.app_binary_observation.evidence_signature)],
    ['presentation.html',`<main>${entities(presentation.envelope.canonical_record.provider_identity)}</main>`],
    ['render.html',`<div>${split(observations.render_attestation.evidence_signature.toUpperCase())}</div>`],
    ['fetch.txt',entities(percent(observations.fetch_observation.evidence_signature))],
  ];
  try{
    for(const [name,content] of cases){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.throws(()=>assertInternalNonpublication(dist,repo),/licensed-delivery fixture scalar fingerprint/,name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('nonpublication rejects encoded licensed fixture scalars in HTML attributes',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-fixture-attribute-nonpub-'));
  const inputFixture=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/synthetic-input.json')));
  const presentation=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/presentation.synthetic.json')));
  const observations=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/observations.synthetic.json')));
  const percent=(value,upper=false)=>[...Buffer.from(value)].map(byte=>`%${byte.toString(16).padStart(2,'0')[upper?'toUpperCase':'toLowerCase']()}`).join('');
  const entities=value=>[...value].map(character=>`&#${character.codePointAt(0)};`).join('');
  const cases=[
    ['entity-key.html',`<DIV DATA-LICENSED="${entities(inputFixture.key)}"></DIV>`],
    ['percent-signature.html',`<span data-evidence='${percent(observations.fetch_observation.evidence_signature)}'></span>`],
    ['upper-percent-digest.htm',`<template DATA-DIGEST=${percent(presentation.envelope.record_revision,true)}></template>`],
    ['nested-encoding.html',`<meta content="${percent(entities(observations.app_binary_observation.evidence_signature))}">`],
  ];
  try{
    for(const [name,content] of cases){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.throws(()=>assertInternalNonpublication(dist,repo),/licensed-delivery fixture scalar fingerprint/,name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('nonpublication rejects raw, encoded, nested, and fragmented internal material in HTML comments',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-comment-nonpub-'));
  const terms=readFileSync(resolve(repo,'reviews/licensed-delivery/v1/terms.counsel-draft.md'),'utf8');
  const counsel=terms.split(/\n\s*\n/).find(value=>value.includes('Responses and presentation tokens')).replace(/\s+/g,' ').trim();
  const presentation=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/presentation.synthetic.json')));
  const schema='Internal licensed-delivery v1 closed schema bundle',fixture=presentation.envelope.canonical_record.provider_identity;
  const percent=value=>[...Buffer.from(value)].map(byte=>`%${byte.toString(16).padStart(2,'0')}`).join('');
  const entities=value=>[...value].map(character=>`&#x${character.codePointAt(0).toString(16)};`).join('');
  const js=value=>[...value].map(character=>`\\u${character.codePointAt(0).toString(16).padStart(4,'0')}`).join('');
  const split=value=>{const at=Math.floor(value.length/2);return `${value.slice(0,at)}<i></i>${value.slice(at)}`;};
  const cases=[
    ['raw-marker.html','reviews/licensed-delivery'],
    ['raw-fingerprint.html',schema],
    ['entity-schema.html',entities(schema)],
    ['percent-fixture.html',percent(fixture)],
    ['javascript-counsel.html',js(counsel)],
    ['mixed-fixture.html',entities(percent(fixture))],
    ['nested-schema.html',js(entities(percent(schema)))],
    ['case-fragmented-schema.html',split(schema.toUpperCase())],
    ['tag-fragmented-counsel.html',split(counsel)],
  ];
  try{
    for(const [name,value] of cases){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),`<!doctype html><p>Ordinary public content.</p><!--${value}-->`);assert.throws(()=>assertInternalNonpublication(dist,repo),/marker|scalar fingerprint/,name);}
    for(const [index,value] of ['Deployment note: public assets generated successfully.','TODO: improve public hotline navigation.','<i>Ordinary</i> public comment with %zz and \\u0ZZZ.'].entries()){const dist=resolve(root,`control-${index}`);mkdirSync(dist);writeFileSync(resolve(dist,'public.html'),`<main>Public hotline directory.</main><!--${value}-->`);assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo),value);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('licensed fixture normalized fingerprints permit ordinary artifacts and isolated common values',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-fixture-controls-'));
  const controls=[
    ['public.html','<main><h1>Public hotline directory</h1><p>Current service information for visitors.</p></main>'],
    ['public.txt','Public application help and contact information.'],
    ['public.json',JSON.stringify({status:'active',platform:'ios',updated_at:'2026-08-17T10:00:00.000Z'})],
    ['common.txt','active outward binary presentation render fetch ios registered_capture_service static_digest_scan_v1'],
    ['attributes.html','<section data-status="active" data-platform="ios" aria-label="Public hotline directory" title="Current service information"></section>'],
  ];
  try{
    for(const [name,content] of controls){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo),name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('licensed contract normalized fingerprints permit ordinary and common public content',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-contract-controls-'));
  const controls=[
    ['public.html','<main>Licensed application delivery information for the public.</main>'],
    ['public.txt','A future authenticated service may use a runtime contract after review.'],
    ['public.json',JSON.stringify({cache_control:'private, no-store',schema_version:'1.0',status:'active'})],
    ['attributes.html','<section data-delivery="licensed" data-contract="public" title="Application information"></section>'],
  ];
  try{
    for(const [name,content] of controls){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),content);assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo),name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('nonpublication strictly decodes BOM-marked UTF-16 artifacts before every scan class',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-utf16-nonpub-'));
  const schemas=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/schemas.json'))),fixture=JSON.parse(readFileSync(resolve(repo,'reviews/licensed-delivery/v1/fixtures/presentation.synthetic.json')));
  const counsel=readFileSync(resolve(repo,'reviews/licensed-delivery/v1/terms.counsel-draft.md'),'utf8').split(/\n\s*\n/).find(value=>value.includes('Responses and presentation tokens')).replace(/\s+/g,' ').trim();
  const schema='Internal licensed-delivery v1 closed schema bundle',provider=fixture.envelope.canonical_record.provider_identity;
  const utf16=(text,endian)=>{const le=Buffer.from(text,'utf16le');if(endian==='le')return Buffer.concat([Buffer.from([0xff,0xfe]),le]);const be=Buffer.alloc(le.length);for(let i=0;i<le.length;i+=2){be[i]=le[i+1];be[i+1]=le[i];}return Buffer.concat([Buffer.from([0xfe,0xff]),be]);};
  const cases=[
    ['marker-le.txt','reviews/licensed-delivery','le'],['marker-be.html','<!--reviews/licensed-delivery-->','be'],
    ['schema-le.js',`const value=${JSON.stringify(schema)};`,'le'],['schema-be.html',`<script>const value=${JSON.stringify(schema)}</script>`,'be'],
    ['fixture-le.json',JSON.stringify(fixture.envelope.canonical_record),'le'],['fixture-be.js',`const provider=${JSON.stringify(provider)};`,'be'],
    ['counsel-le.html',`<article>${counsel}</article>`,'le'],['counsel-be.txt',counsel,'be'],
    ['semantic-le.json',JSON.stringify(schemas),'le'],['semantic-be.json',JSON.stringify(schemas),'be'],
  ];
  try{for(const [name,value,endian] of cases){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),utf16(value,endian));assert.throws(()=>assertInternalNonpublication(dist,repo),/marker|semantic section|scalar fingerprint/,name);}}finally{rmSync(root,{recursive:true,force:true});}
});
test('artifact text decoding fails closed for malformed UTF-16 and keeps UTF-8 BOM, binary, and Unicode behavior exact',()=>{
  assert.throws(()=>decodeArtifactText(Buffer.from([0xff,0xfe,0x41]),'odd'),/odd-length/);
  for(const bytes of [[0xff,0xfe,0x00,0xd8],[0xfe,0xff,0xdc,0x00],[0xff,0xfe,0x00,0xd8,0x41,0x00]])assert.throws(()=>decodeArtifactText(Buffer.from(bytes),'surrogate'),/surrogate/);
  assert.equal(decodeArtifactText(Buffer.from([0xef,0xbb,0xbf,0x68,0x69]),'utf8-bom'),'hi');
  assert.throws(()=>decodeArtifactText(Buffer.from([0xef,0xbb,0xbf,0xff]),'utf8-bom-bad'),/malformed BOM-marked UTF-8/);
  assert.equal(decodeArtifactText(Buffer.from([0,0xff,1,0x80]),'binary.bin'),undefined);
  assert.equal(decodeArtifactText(Buffer.from('Harmless café — 世界 😀'),'unicode'),'Harmless café — 世界 😀');
  const oversized=Buffer.alloc(2+(32*1024*1024+1)*2);oversized[0]=0xff;oversized[1]=0xfe;for(let i=2;i<oversized.length;i+=2)oversized[i]=0x61;
  assert.throws(()=>decodeArtifactText(oversized,'oversized'),/exceeds bounded/);
});
test('legacy octal decoding implements ECMAScript maximal munch and preserves invalid or escaped forms',()=>{
  assert.equal(decodeLegacyOctalEscapes(String.raw`\0x\00\07\10\77\100\377\400`),`\0x\0\x07\b?@ÿ 0`);
  assert.equal(decodeLegacyOctalEscapes(String.raw`\18\278\378\777`),`${String.fromCharCode(1)}8${String.fromCharCode(23)}8${String.fromCharCode(31)}8?7`);
  assert.equal(decodeLegacyOctalEscapes(String.raw`\08\09\8\9\\141 text 123`),String.raw`\08\09\8\9\\141 text 123`);
  assert.equal(decodeLegacyOctalEscapes(String.raw`a\141b\142c\143d`),'aabbccd');
});
test('nonpublication conservatively scans valid legacy octal in classic and ambiguous contexts but not strict source',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-octal-nonpub-')),marker='reviews/licensed-delivery';
  const octal=value=>[...value].map(character=>`\\${character.charCodeAt(0).toString(8)}`).join('');
  const encoded=octal(marker),mixed=`${octal('reviews/licensed')}\\x2d${octal('delivery')}`;
  const rejects=[['classic.js',`const a='${encoded}', b='public', c='${mixed}';`],['multiple.txt',`before ${encoded} middle ${encoded} after`],['script.html',`<script>const x='${encoded}'</script>`],['comment.html',`<!--${encoded}-->`],['attribute.html',`<p data-note="${encoded}">public</p>`],['unknown.dat',`{"note":"${encoded}"}`]];
  try{
    for(const [name,value] of rejects){const dist=resolve(root,name.replace('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),value);assert.throws(()=>assertInternalNonpublication(dist,repo),/marker/,name);}
    for(const [name,value] of [['strict.js',`'use strict'; const x='${encoded}';`],['module.mjs',`export const x='${encoded}';`],['module.html',`<script type="module">const x='${encoded}'</script>`],['data-script.html',`<script type="application/json">{"note":"${encoded}"}</script>`],['escaped.js',String.raw`const x="\\162\\145\\166";`],['invalid.js',String.raw`const x="\8\9\08\09";`],['public.txt',String.raw`Public build 123 077 400 and \\141 documentation.`],['unicode.txt','Public café 世界 😀']]){const dist=resolve(root,`control-${name.replace('.','-')}`);mkdirSync(dist);writeFileSync(resolve(dist,name),value);assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo),name);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('HTML script type classification follows classic JavaScript MIME essence semantics and fails malformed values closed',()=>{
  const legacy=['application/ecmascript','application/javascript','application/x-ecmascript','application/x-javascript','text/ecmascript','text/javascript','text/javascript1.0','text/javascript1.1','text/javascript1.2','text/javascript1.3','text/javascript1.4','text/javascript1.5','text/jscript','text/livescript','text/x-ecmascript','text/x-javascript'];
  for(const essence of legacy){assert.equal(classifyHtmlScriptType(essence),'classic',essence);assert.equal(classifyHtmlScriptType(` \t${essence.toUpperCase()} ; Charset=UTF-8 `),'classic',`${essence} case/space/parameter`);assert.equal(classifyHtmlScriptType(`${essence};charset="utf-8";version='legacy'`),'classic',`${essence} quoted/unquoted`);}
  for(const value of [undefined,'',' \t\n\r\f '])assert.equal(classifyHtmlScriptType(value),'classic',String(value));
  for(const value of ['module',' MODULE ','importmap','SPECULATIONRULES','application/json','text/plain','text/javascriptish','text/javascript;','text/javascript;charset','text/javascript;=utf-8','text/javascript;charset=','text/javascript;charset="unterminated','text/javascript;charset="bad\nvalue"','text /javascript','text/javascript,application/json'])assert.equal(classifyHtmlScriptType(value),value.trim().toLowerCase()==='module'?'strict':'disabled',value);
});
test('HTML script execution modes apply octal and NonEscapeCharacter decoding only to executable classic scripts',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-script-types-')),marker='reviews/licensed-delivery',octal=[...marker].map(c=>`\\${c.charCodeAt(0).toString(8)}`).join(''),nonEscape='reviews/licen\\sed/delivery',split='Internal licen\\sed-delivery v1 closed schema bundle';
  const classicTypes=['',' type=" \tTeXt/JaVaScRiPt ; charset=UTF-8 "',' type=text/javascript',' type=\'application/x-javascript;charset="utf-8"\''];
  try{
    for(const [index,type] of classicTypes.entries()){const dist=resolve(root,`classic-${index}`);mkdirSync(dist);writeFileSync(resolve(dist,'index.html'),`<script${type}>const a='${octal}',b='${nonEscape}',c='${split}'</script>`);assert.throws(()=>assertInternalNonpublication(dist,repo),/marker|fingerprint/,type);}
    for(const [index,type] of ['module','importmap','speculationrules','application/json','text/javascript;charset="unterminated'].entries()){const dist=resolve(root,`disabled-${index}`);mkdirSync(dist);writeFileSync(resolve(dist,'index.html'),`<script type='${type}'>const a='${octal}',b='${nonEscape}'</script>`);assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo),type);}
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('public dist rejects archive/compression extensions, signatures, polyglots, and links while allowing only exact source-controlled root images',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-archives-'));
  const extensions=['gz','br','zip','7z','bz2','xz','tar','tgz','tbz2','txz','rar','zst','jar','whl','cab','cpio','rpm','ar','iso'];
  const signatures=[['gzip',[0x1f,0x8b,8]],['zip',[0x50,0x4b,3,4]],['7z',[0x37,0x7a,0xbc,0xaf,0x27,0x1c]],['bzip2',[0x42,0x5a,0x68]],['xz',[0xfd,0x37,0x7a,0x58,0x5a,0]],['rar',[0x52,0x61,0x72,0x21,0x1a,7]],['zstd',[0x28,0xb5,0x2f,0xfd]],['cab',[0x4d,0x53,0x43,0x46]],['rpm',[0xed,0xab,0xee,0xdb]],['cpio',Buffer.from('070701')]];
  const reject=(name,bytes)=>{const dist=resolve(root,name.replaceAll('.','-'));mkdirSync(dist);writeFileSync(resolve(dist,name),bytes);assert.throws(()=>assertInternalNonpublication(dist,repo),/compressed\/archive artifact/,name);};
  try{
    for(const extension of extensions)reject(`harmless.${extension}`,Buffer.from('ordinary harmless archive payload'));
    for(const [name,bytes] of signatures)reject(`${name}.bin`,Buffer.from(bytes));
    const tar=Buffer.alloc(512);tar.write('ustar',257);reject('renamed.dat',tar);
    reject('licensed.txt.gz',Buffer.concat([Buffer.from([0x1f,0x8b,8]),Buffer.from('reviews/licensed-delivery')]));
    reject('photo.JPG',Buffer.concat([Buffer.from([0xff,0xd8,0xff]),Buffer.from('public'),Buffer.from([0x50,0x4b,3,4])]));
    for(const name of ['favicon-32x32.png','favicon-192x192.png','apple-touch-icon.png','pwa-icon-512.png','social-card.png']){const dist=resolve(root,`allowed-${name}`);mkdirSync(dist);writeFileSync(resolve(dist,name),readFileSync(resolve(repo,'web/public',name)));assert.doesNotThrow(()=>assertInternalNonpublication(dist,repo),name);}
    const image=readFileSync(resolve(repo,'web/public/social-card.png')),moved=resolve(root,'moved-image');mkdirSync(resolve(moved,'assets'),{recursive:true});writeFileSync(resolve(moved,'assets/social-card.png'),image);assert.throws(()=>assertInternalNonpublication(moved,repo),/explicitly source-allowlisted/);
    const modified=resolve(root,'modified-image');mkdirSync(modified);const changed=Buffer.from(image);changed[changed.length-1]^=1;writeFileSync(resolve(modified,'social-card.png'),changed);assert.throws(()=>assertInternalNonpublication(modified,repo),/explicitly source-allowlisted/);
    for(const name of ['social-card.png\\copy','social-card.png\u0001copy']){const dist=resolve(root,`noncanonical-${Buffer.from(name).toString('hex')}`);mkdirSync(dist);writeFileSync(resolve(dist,name),image);assert.throws(()=>assertInternalNonpublication(dist,repo),/noncanonical public artifact relative path/);}
    const links=resolve(root,'links');mkdirSync(links);writeFileSync(resolve(links,'target.bin'),Buffer.from([0,0xff]));symlinkSync('target.bin',resolve(links,'alias.bin'));assert.throws(()=>assertInternalNonpublication(links,repo),/symbolic link/);
    rmSync(resolve(links,'alias.bin'));linkSync(resolve(links,'target.bin'),resolve(links,'hard.bin'));assert.throws(()=>assertInternalNonpublication(links,repo),/hard-linked artifact/);
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('generated release inventories cannot self-authorize opaque artifacts or renamed Brotli streams',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-opaque-deny-')),digest=bytes=>`sha256:${createHash('sha256').update(bytes).digest('hex')}`;
  const fixture=(label,path,bytes,inventory=true)=>{const dist=resolve(root,label),target=resolve(dist,path);mkdirSync(resolve(target,'..'),{recursive:true});writeFileSync(target,bytes);if(inventory){const releaseDir=resolve(dist,'release/v1'),entry={path:`/${path}`,bytes:bytes.length,sha256:digest(bytes)};mkdirSync(releaseDir,{recursive:true});const indexBytes=Buffer.from(JSON.stringify({artifacts:[entry]}));writeFileSync(resolve(releaseDir,'artifacts.json'),indexBytes);writeFileSync(resolve(releaseDir,'release.json'),JSON.stringify({artifact_index:{sha256:digest(indexBytes),artifact_count:1},relationships:{[`/${path}`]:entry}}));}return dist;};
  const reject=(label,path,bytes,inventory=false)=>assert.throws(()=>assertInternalNonpublication(fixture(label,path,bytes,inventory),repo),/opaque public artifact|marker/,label);
  const internal=Buffer.from('reviews/licensed-delivery'),standalone=brotliCompressSync(internal),largeSource=Buffer.alloc(33*1024*1024);let state=0x6d2b79f5;for(let i=0;i<largeSource.length;i++){state^=state<<13;state^=state>>>17;state^=state<<5;largeSource[i]=state&0xff;}const large=brotliCompressSync(largeSource,{params:{[zlibConstants.BROTLI_PARAM_QUALITY]:0,[zlibConstants.BROTLI_PARAM_MODE]:zlibConstants.BROTLI_MODE_GENERIC}}),emptyTail=Buffer.concat([brotliCompressSync(Buffer.alloc(0)),internal]),validTail=Buffer.concat([standalone,Buffer.from('tail')]),prefixed=Buffer.concat([Buffer.from('prefix'),standalone]);assert.ok(large.length>32*1024*1024,'fixture must be a valid Brotli input whose compressed bytes exceed 32 MiB');
  try{
    const variants=[['standalone',standalone],['oversized',large],['empty-tail',emptyTail],['valid-tail',validTail],['prefixed',prefixed]],extensions=[['bin','.bin'],['known-opaque','.png'],['unknown','.opaque'],['extensionless','']];
    for(const [variant,bytes] of variants)for(const [kind,extension] of extensions)reject(`${variant}-${kind}`,`payload${extension}`,bytes);
    const ordinary=Buffer.from([0x00,0x11,0x22,0x80,0xfe,0x7f]);for(const [kind,extension] of extensions)reject(`ordinary-${kind}`,`ordinary${extension}`,ordinary);
    for(const [kind,extension] of extensions)reject(`self-inventoried-${kind}`,`invented${extension}`,ordinary,true);
    const image=readFileSync(resolve(repo,'web/public/social-card.png'));reject('self-inventoried-image','invented.png',image,true);
    // Even an internally consistent path/byte-count/SHA inventory and matching
    // release relationship is generated output and confers no authority.
    reject('path-hash-bytes-self-authorization','arbitrary.bin',ordinary,true);
  }finally{rmSync(root,{recursive:true,force:true});}
});
test('only the exact generated gzip compatibility artifact is allowed, identity-bound, bounded, and decompressed-scanned',()=>{
  const repo=resolve(import.meta.dirname,'../../../..'),root=mkdtempSync(resolve(tmpdir(),'licensed-gzip-compat-')),digest=bytes=>`sha256:${createHash('sha256').update(bytes).digest('hex')}`;
  const fixture=(name,raw=Buffer.from('{"public":true}'))=>{const dist=resolve(root,name),api=resolve(dist,'api/v1'),releaseDir=resolve(dist,'release/v1');mkdirSync(api,{recursive:true});mkdirSync(releaseDir,{recursive:true});const compressed=gzipSync(raw,{level:9,mtime:0}),rawEntry={path:'/api/v1/traveler-cards.json',sha256:digest(raw),bytes:raw.length},gzipEntry={path:'/api/v1/traveler-cards.json.gz',sha256:digest(compressed),bytes:compressed.length};writeFileSync(resolve(api,'traveler-cards.json'),raw);writeFileSync(resolve(api,'traveler-cards.json.gz'),compressed);writeFileSync(resolve(api,'manifest.json'),JSON.stringify({traveler_card_artifacts:{raw:{path:'traveler-cards.json',bytes:raw.length,sha256:digest(raw)},gzip_compatibility:{path:'traveler-cards.json.gz',bytes:compressed.length,sha256:digest(compressed),decompressed_bytes:raw.length,decompressed_sha256:digest(raw)}}}));writeFileSync(resolve(releaseDir,'artifacts.json'),JSON.stringify({artifacts:[rawEntry,gzipEntry]}));writeFileSync(resolve(releaseDir,'release.json'),JSON.stringify({relationships:{[rawEntry.path]:rawEntry,[gzipEntry.path]:gzipEntry}}));return {dist,api,releaseDir,compressed};};
  try{
    const valid=fixture('valid');assert.doesNotThrow(()=>assertInternalNonpublication(valid.dist,repo));
    const leaked=fixture('leaked',Buffer.from('reviews/licensed-delivery'));assert.throws(()=>assertInternalNonpublication(leaked.dist,repo),/marker/);
    const corrupt=fixture('corrupt');writeFileSync(resolve(corrupt.api,'traveler-cards.json.gz'),Buffer.from([0x1f,0x8b,0x08]));assert.throws(()=>assertInternalNonpublication(corrupt.dist,repo),/boundedly gunzipped/);
    const wrongRaw=fixture('wrong-raw');writeFileSync(resolve(wrongRaw.api,'traveler-cards.json'),Buffer.from('{"different":true}'));assert.throws(()=>assertInternalNonpublication(wrongRaw.dist,repo),/canonical raw JSON bytes/);
    const wrongManifest=fixture('wrong-manifest');const manifestPath=resolve(wrongManifest.api,'manifest.json'),manifest=JSON.parse(readFileSync(manifestPath));manifest.traveler_card_artifacts.gzip_compatibility.bytes++;writeFileSync(manifestPath,JSON.stringify(manifest));assert.throws(()=>assertInternalNonpublication(wrongManifest.dist,repo),/manifest hashes or sizes mismatch/);
    const wrongRelease=fixture('wrong-release');const indexPath=resolve(wrongRelease.releaseDir,'artifacts.json'),index=JSON.parse(readFileSync(indexPath));index.artifacts[1].bytes++;writeFileSync(indexPath,JSON.stringify(index));assert.throws(()=>assertInternalNonpublication(wrongRelease.dist,repo),/release hashes or sizes mismatch/);
    const oversized=fixture('oversized',Buffer.alloc(1024*1024+1,0x20));assert.throws(()=>assertInternalNonpublication(oversized.dist,repo),/boundedly gunzipped/);
    const renamed=fixture('renamed');writeFileSync(resolve(renamed.api,'copy.json.gz'),renamed.compressed);assert.throws(()=>assertInternalNonpublication(renamed.dist,repo),/compressed\/archive artifact/);
  }finally{rmSync(root,{recursive:true,force:true});}
});
