import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';

const INVALID_INPUT = 'invalid control-plane input';
const TOP_LEVEL_KEYS = ['contract_status','effective_at','organizations','projects','role_assignments','key_references','hosted_config_versions','transition_scenarios'];
const COMMAND_KEYS = ['id','request_id','action','organization_id','project_id','actor_principal_id','target_config_version_id','expected_active_config_version_id','timestamp'];
const ID = Object.freeze({
  organization_id:/^org_demo_[a-z0-9]{4,24}$/,
  project_id:/^project_demo_[a-z0-9]{4,24}$/,
  actor_principal_id:/^principal_demo_[a-z0-9]{4,24}$/,
  target_config_version_id:/^config_demo_[a-z0-9]{4,24}$/,
  expected_active_config_version_id:/^config_demo_[a-z0-9]{4,24}$/,
  id:/^command_demo_[a-z0-9]{4,24}$/,
  request_id:/^request_demo_[a-z0-9]{4,24}$/
});
export const ROLE_PERMISSIONS=Object.freeze({owner:['audit.read','configs.manage','configs.read','keys.manage','keys.read','organization.read','project.configure','project.read','roles.manage','roles.read'],admin:['audit.read','configs.manage','configs.read','keys.manage','keys.read','organization.read','project.configure','project.read','roles.read'],developer:['configs.manage','configs.read','keys.read','organization.read','project.read'],viewer:['audit.read','configs.read','keys.read','organization.read','project.read','roles.read']});

const clone=structuredClone, sorted=x=>[...x].sort(), time=x=>Date.parse(x);
const by=(xs,get=x=>x.id)=>new Map(xs.map(x=>[get(x),x]));
const canonical=v=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
const digestContent=content=>`sha256:${createHash('sha256').update(canonical(content)).digest('hex')}`;

function canonicalUtc(value){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString()===value;}
function safeTree(value,seen=new Set()){
  if(value===null||typeof value==='string'||typeof value==='boolean')return;
  if(typeof value==='number'){if(Number.isFinite(value))return;throw new Error(INVALID_INPUT);}
  if(typeof value!=='object'||seen.has(value))throw new Error(INVALID_INPUT);
  seen.add(value);
  if(Array.isArray(value)?Object.getPrototypeOf(value)!==Array.prototype:Object.getPrototypeOf(value)!==Object.prototype)throw new Error(INVALID_INPUT);
  if(Object.getOwnPropertySymbols(value).length)throw new Error(INVALID_INPUT);
  const descriptors=Object.getOwnPropertyDescriptors(value);
  for(const [key,descriptor] of Object.entries(descriptors)){
    if('get' in descriptor||'set' in descriptor||(!descriptor.enumerable&&!(Array.isArray(value)&&key==='length')))throw new Error(INVALID_INPUT);
  }
  if(Array.isArray(value)){if(Object.keys(value).length!==value.length)throw new Error(INVALID_INPUT);for(let i=0;i<value.length;i++)if(!Object.hasOwn(value,i))throw new Error(INVALID_INPUT);}
  for(const [key,descriptor] of Object.entries(descriptors))if(!(Array.isArray(value)&&key==='length'))safeTree(descriptor.value,seen);
  seen.delete(value);
}
function exactKeys(value,expected){assert.deepEqual(Object.keys(value).sort(),[...expected].sort());}
const PATTERN={org:/^org_demo_[a-z0-9]{4,24}$/,project:/^project_demo_[a-z0-9]{4,24}$/,principal:/^principal_demo_[a-z0-9]{4,24}$/,assignment:/^assignment_demo_[a-z0-9]{4,24}$/,key:/^keyref_demo_[a-z0-9]{4,24}$/,config:/^config_demo_[a-z0-9]{4,24}$/,scenario:/^scenario_demo_[a-z0-9]{4,24}$/,command:/^command_demo_[a-z0-9]{4,24}$/,request:/^request_demo_[a-z0-9]{4,24}$/,audit:/^audit_demo_[a-z0-9]{4,24}$/};
function ids(values,pattern){for(const value of values)assert.match(value,pattern);}
function oneOf(value,values){assert.ok(values.includes(value));}
function integer(value,min,max){assert.ok(Number.isInteger(value)&&value>=min&&value<=max);}
function list(value,{min=0,max,unique=false,item}){assert.ok(Array.isArray(value)&&value.length>=min&&value.length<=max);if(unique)assert.equal(new Set(value).size,value.length);for(const entry of value)item(entry);}
function nullable(value,check){if(value!==null)check(value);}
const label=value=>{assert.equal(typeof value,'string');assert.ok(value.length<=80);assert.match(value,/^Synthetic [A-Za-z0-9 -]{1,48} \(non-customer\)$/);};
const origin=value=>{assert.equal(typeof value,'string');assert.ok(value.length<=160);assert.match(value,/^https:\/\/[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)*\.example\.invalid$/);validOrigin(value);};
const utc=value=>assert.ok(canonicalUtc(value));
const identifier=(pattern)=>value=>{assert.equal(typeof value,'string');assert.match(value,pattern);};
const enumOf=(values)=>value=>oneOf(value,values);
const idCheck=Object.fromEntries(Object.entries(PATTERN).map(([name,pattern])=>[name,identifier(pattern)]));
const arrayOf=(item,max,min=0,unique=false)=>value=>list(value,{min,max,unique,item});
function modelShape(model){
  const state=enumOf(['active','suspended','archived']);
  for(const org of model.organizations){exactKeys(org,['id','display_label','state','policy_version','contract_version','project_ids','role_assignment_ids','created_at','updated_at']);idCheck.org(org.id);label(org.display_label);state(org.state);integer(org.policy_version,1,9999);assert.equal(org.contract_version,'organizations/v1');arrayOf(idCheck.project,32,0,true)(org.project_ids);arrayOf(idCheck.assignment,64,0,true)(org.role_assignment_ids);utc(org.created_at);utc(org.updated_at);}
  for(const project of model.projects){exactKeys(project,['id','organization_id','display_label','state','allowed_origins','api_major_allowlist','key_reference_ids','hosted_config_version_ids','active_hosted_config_version_id','created_at','updated_at']);idCheck.project(project.id);idCheck.org(project.organization_id);label(project.display_label);state(project.state);arrayOf(origin,16,0,true)(project.allowed_origins);list(project.api_major_allowlist,{min:1,max:4,unique:true,item:x=>integer(x,1,9)});arrayOf(idCheck.key,32,0,true)(project.key_reference_ids);arrayOf(idCheck.config,64,0,true)(project.hosted_config_version_ids);nullable(project.active_hosted_config_version_id,idCheck.config);utc(project.created_at);utc(project.updated_at);}
  const permission=enumOf(Object.values(ROLE_PERMISSIONS).flat());
  for(const a of model.role_assignments){exactKeys(a,['id','principal_id','organization_id','project_id','role','permissions','state','effective_at','revoked_at','created_at','updated_at']);idCheck.assignment(a.id);idCheck.principal(a.principal_id);idCheck.org(a.organization_id);nullable(a.project_id,idCheck.project);oneOf(a.role,['owner','admin','developer','viewer']);list(a.permissions,{min:1,max:10,unique:true,item:permission});oneOf(a.state,['active','suspended','revoked']);utc(a.effective_at);nullable(a.revoked_at,utc);utc(a.created_at);utc(a.updated_at);}
  for(const key of model.key_references){exactKeys(key,['id','organization_id','project_id','api_major','permissions','quota_summary','state','not_before','expires_at','rotation_predecessor_id','created_at','updated_at']);idCheck.key(key.id);idCheck.org(key.organization_id);idCheck.project(key.project_id);integer(key.api_major,1,9);list(key.permissions,{min:1,max:2,unique:true,item:enumOf(['api.read','widget.resolve'])});exactKeys(key.quota_summary,['window','request_limit']);oneOf(key.quota_summary.window,['minute','hour','day']);integer(key.quota_summary.request_limit,1,1000000);oneOf(key.state,['pending','active','suspended','expired','revoked']);utc(key.not_before);nullable(key.expires_at,utc);nullable(key.rotation_predecessor_id,idCheck.key);utc(key.created_at);utc(key.updated_at);}
  for(const version of model.hosted_config_versions){exactKeys(version,['content','content_digest','lifecycle','signature_metadata']);const c=version.content;exactKeys(c,['id','organization_id','project_id','revision','allowed_origins','widget_major','presentation','resolver_defaults','previous_version_id','created_at']);idCheck.config(c.id);idCheck.org(c.organization_id);idCheck.project(c.project_id);integer(c.revision,1,1000000);arrayOf(origin,16,1,true)(c.allowed_origins);integer(c.widget_major,1,9);exactKeys(c.presentation,['theme','density','show_attribution','max_results']);oneOf(c.presentation.theme,['light','dark','system']);oneOf(c.presentation.density,['compact','comfortable']);assert.equal(typeof c.presentation.show_attribution,'boolean');integer(c.presentation.max_results,1,20);exactKeys(c.resolver_defaults,['language_mode','sort_mode','empty_state']);oneOf(c.resolver_defaults.language_mode,['document','browser']);oneOf(c.resolver_defaults.sort_mode,['source_order','alphabetical']);oneOf(c.resolver_defaults.empty_state,['hidden','generic_message']);nullable(c.previous_version_id,idCheck.config);utc(c.created_at);assert.match(version.content_digest,/^sha256:[0-9a-f]{64}$/);exactKeys(version.lifecycle,['state','updated_at']);oneOf(version.lifecycle.state,['draft','active','retired']);utc(version.lifecycle.updated_at);exactKeys(version.signature_metadata,['status','algorithm','key_reference']);assert.equal(version.signature_metadata.status,'design-only-not-signed');assert.equal(version.signature_metadata.algorithm,'none');assert.equal(version.signature_metadata.key_reference,null);}
  for(const scenario of model.transition_scenarios){exactKeys(scenario,['id','before','command','result','audit_event','expected_after']);idCheck.scenario(scenario.id);const b=scenario.before;exactKeys(b,['project_id','active_config_version_id','active_config_state','target_config_version_id','target_config_state']);idCheck.project(b.project_id);idCheck.config(b.active_config_version_id);assert.equal(b.active_config_state,'active');idCheck.config(b.target_config_version_id);oneOf(b.target_config_state,['draft','retired']);structuralCommand(scenario.command);const accepted=scenario.result.outcome==='accepted';resultShape(scenario.result,accepted);auditShape(scenario.audit_event,accepted);afterShape(scenario.expected_after,accepted);}
}
function resultShape(result,accepted){exactKeys(result,accepted?['command_id','request_id','outcome','reason_code','changed','previous_active_config_version_id','active_config_version_id','timestamp']:['command_id','request_id','outcome','reason_code','changed','active_config_version_id','timestamp']);idCheck.command(result.command_id);idCheck.request(result.request_id);assert.equal(result.outcome,accepted?'accepted':'rejected');if(accepted){assert.equal(result.reason_code,'activated_prior_content_version');assert.equal(result.changed,true);idCheck.config(result.previous_active_config_version_id);idCheck.config(result.active_config_version_id);}else{oneOf(result.reason_code,['authorization_denied','binding_mismatch','concurrent_state_mismatch','invalid_lifecycle']);assert.equal(result.changed,false);nullable(result.active_config_version_id,idCheck.config);}utc(result.timestamp);}
function auditShape(a,accepted){exactKeys(a,['id','command_id','action','outcome','reason_code','actor_principal_id','organization_id','project_id','config_version_id','key_reference_id','assignment_id','request_id','timestamp']);idCheck.audit(a.id);idCheck.command(a.command_id);assert.equal(a.action,'hosted_config.activated');assert.equal(a.outcome,accepted?'accepted':'rejected');if(accepted)assert.equal(a.reason_code,'policy_allowed');else oneOf(a.reason_code,['authorization_denied','binding_mismatch','concurrent_state_mismatch','invalid_lifecycle']);idCheck.principal(a.actor_principal_id);idCheck.org(a.organization_id);idCheck.project(a.project_id);idCheck.config(a.config_version_id);assert.equal(a.key_reference_id,null);assert.equal(a.assignment_id,null);idCheck.request(a.request_id);utc(a.timestamp);}
function afterShape(a,accepted){exactKeys(a,accepted?['project_id','active_config_version_id','active_config_state','prior_config_version_id','prior_config_state','updated_at']:['unchanged','project_id','active_config_version_id','active_config_state','target_config_version_id','target_config_state']);if(!accepted)assert.equal(a.unchanged,true);idCheck.project(a.project_id);idCheck.config(a.active_config_version_id);assert.equal(a.active_config_state,'active');if(accepted){idCheck.config(a.prior_config_version_id);assert.equal(a.prior_config_state,'retired');utc(a.updated_at);}else{idCheck.config(a.target_config_version_id);oneOf(a.target_config_state,['draft','retired']);}}
function structuralCommand(command){assert.ok(command&&Object.getPrototypeOf(command)===Object.prototype);exactKeys(command,COMMAND_KEYS);for(const [name,pattern] of Object.entries(ID)){assert.equal(typeof command[name],'string');assert.match(command[name],pattern);}assert.equal(command.action,'activate_hosted_config_version');utc(command.timestamp);}
function structuralModel(model){
  safeTree(model);
  assert.ok(model&&Object.getPrototypeOf(model)===Object.prototype);exactKeys(model,TOP_LEVEL_KEYS);
  assert.equal(model.contract_status,'foundation-design-contract-not-deployed');utc(model.effective_at);
  const limits={organizations:16,projects:32,role_assignments:64,key_references:64,hosted_config_versions:64,transition_scenarios:16};
  for(const [name,max] of Object.entries(limits))assert.ok(Array.isArray(model[name])&&model[name].length<=max);
  modelShape(model);
}
function structuralInput(model,command){
  structuralModel(model);safeTree(command);structuralCommand(command);
}
function exactIds(actual,children,predicate,get=x=>x.id){assert.deepEqual(actual,sorted(children.filter(predicate).map(get)));}
function validOrigin(origin){const u=new URL(origin);assert.equal(origin,origin.toLowerCase());assert.ok(!origin.includes('%'));assert.equal(u.protocol,'https:');assert.equal(u.username,'');assert.equal(u.password,'');assert.equal(u.port,'');assert.equal(u.pathname,'/');assert.equal(u.search,'');assert.equal(u.hash,'');assert.equal(origin,`https://${u.hostname}`);assert.ok(u.hostname.endsWith('.example.invalid'));const labels=u.hostname.slice(0,-'.example.invalid'.length).split('.');assert.ok(labels.length&&u.hostname.length<=253);for(const label of labels){assert.match(label,/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/);assert.ok(!label.startsWith('xn--'));assert.notEqual(label,'localhost');}assert.ok(!labels.every(label=>/^\d+$/.test(label)));}
function grantAt(model,command){return model.role_assignments.find(a=>a.principal_id===command.actor_principal_id&&a.organization_id===command.organization_id&&(a.project_id===null||a.project_id===command.project_id)&&a.state==='active'&&a.permissions.includes('configs.manage')&&time(a.effective_at)<=time(command.timestamp)&&(a.revoked_at===null||time(command.timestamp)<time(a.revoked_at)));}
function isAncestor(configs,current,target){let cursor=current;const seen=new Set();while(cursor.content.previous_version_id!==null){if(seen.has(cursor.content.id))return false;seen.add(cursor.content.id);const prior=configs.get(cursor.content.previous_version_id);if(!prior)return false;if(prior.content.id===target.content.id)return true;cursor=prior;}return false;}
function auditFor(command,outcome,reason){return{id:`audit_demo_${command.id.slice('command_demo_'.length)}`,command_id:command.id,action:'hosted_config.activated',outcome,reason_code:outcome==='accepted'?'policy_allowed':reason,actor_principal_id:command.actor_principal_id,organization_id:command.organization_id,project_id:command.project_id,config_version_id:command.target_config_version_id,key_reference_id:null,assignment_id:null,request_id:command.request_id,timestamp:command.timestamp};}

function coreInvariant(model){
  const collections=['organizations','projects','role_assignments','key_references'];for(const name of collections)assert.equal(by(model[name]).size,model[name].length);assert.equal(by(model.hosted_config_versions,x=>x.content.id).size,model.hosted_config_versions.length);
  const orgs=by(model.organizations),projects=by(model.projects),keys=by(model.key_references),configs=by(model.hosted_config_versions,x=>x.content.id),effective=time(model.effective_at);
  for(const org of model.organizations){assert.ok(time(org.created_at)<=time(org.updated_at));exactIds(org.project_ids,model.projects,x=>x.organization_id===org.id);exactIds(org.role_assignment_ids,model.role_assignments,x=>x.organization_id===org.id);if(org.state==='active')assert.ok(model.role_assignments.some(a=>a.organization_id===org.id&&a.role==='owner'&&a.project_id===null&&a.state==='active'));}
  for(const project of model.projects){const org=orgs.get(project.organization_id);assert.ok(org);assert.ok(time(project.created_at)<=time(project.updated_at));for(const origin of project.allowed_origins)validOrigin(origin);exactIds(project.key_reference_ids,model.key_references,x=>x.project_id===project.id&&x.organization_id===project.organization_id);exactIds(project.hosted_config_version_ids,model.hosted_config_versions,x=>x.content.project_id===project.id&&x.content.organization_id===project.organization_id,x=>x.content.id);const owned=model.hosted_config_versions.filter(x=>x.content.project_id===project.id&&x.content.organization_id===project.organization_id),active=owned.filter(x=>x.lifecycle.state==='active');if(project.state==='active'){assert.equal(org.state,'active');assert.equal(active.length,1);assert.equal(project.active_hosted_config_version_id,active[0].content.id);}else if(project.state==='suspended'){assert.equal(active.length,0);const pointer=configs.get(project.active_hosted_config_version_id);assert.ok(pointer);assert.equal(pointer.content.organization_id,project.organization_id);assert.equal(pointer.content.project_id,project.id);assert.ok(project.hosted_config_version_ids.includes(pointer.content.id));assert.equal(pointer.lifecycle.state,'retired');}else{assert.equal(active.length,0);assert.equal(project.active_hosted_config_version_id,null);}}
  const activeAssignments=new Set();for(const a of model.role_assignments){const org=orgs.get(a.organization_id);assert.ok(org);assert.equal(['owner','admin'].includes(a.role),a.project_id===null);if(a.project_id!==null)assert.equal(projects.get(a.project_id)?.organization_id,a.organization_id);assert.deepEqual(a.permissions,ROLE_PERMISSIONS[a.role]);assert.ok(time(a.created_at)<=time(a.effective_at)&&time(a.effective_at)<=time(a.updated_at));assert.equal(a.state==='revoked',a.revoked_at!==null);if(a.revoked_at!==null)assert.ok(time(a.revoked_at)>=time(a.effective_at));if(a.state==='active'){assert.equal(org.state,'active');if(a.project_id!==null)assert.equal(projects.get(a.project_id).state,'active');const identity=canonical([a.principal_id,a.organization_id,a.project_id,a.role]);assert.ok(!activeAssignments.has(identity));activeAssignments.add(identity);}}
  const successors=new Map();for(const key of model.key_references){const project=projects.get(key.project_id),org=orgs.get(key.organization_id);assert.equal(project?.organization_id,key.organization_id);assert.ok(project.api_major_allowlist.includes(key.api_major));assert.ok(time(key.created_at)<=time(key.not_before));assert.ok(time(key.not_before)<=time(key.updated_at));if(key.expires_at!==null)assert.ok(time(key.expires_at)>time(key.not_before));if(key.state==='pending')assert.ok(time(key.not_before)>effective);if(key.state==='active'){assert.equal(org.state,'active');assert.equal(project.state,'active');assert.ok(time(key.not_before)<=effective);assert.ok(key.expires_at===null||effective<time(key.expires_at));}if(key.state==='expired'){assert.notEqual(key.expires_at,null);assert.ok(time(key.expires_at)<=effective);}if(['revoked','suspended'].includes(key.state))assert.ok(time(key.updated_at)>=time(key.not_before));if(['active','pending'].includes(key.state)){assert.equal(org.state,'active');assert.equal(project.state,'active');}if(key.rotation_predecessor_id!==null){assert.notEqual(key.rotation_predecessor_id,key.id);assert.equal(successors.has(key.rotation_predecessor_id),false);successors.set(key.rotation_predecessor_id,key.id);}}
  for(const key of model.key_references){const seen=new Set([key.id]);let cursor=key;while(cursor.rotation_predecessor_id!==null){const prior=keys.get(cursor.rotation_predecessor_id);assert.ok(prior);assert.equal(prior.organization_id,key.organization_id);assert.equal(prior.project_id,key.project_id);assert.equal(prior.api_major,key.api_major);assert.deepEqual(prior.permissions,key.permissions);assert.deepEqual(prior.quota_summary,key.quota_summary);assert.ok(time(prior.created_at)<time(cursor.created_at));assert.ok(time(prior.not_before)<time(cursor.not_before));assert.ok(['revoked','expired'].includes(prior.state));assert.ok(!seen.has(prior.id));seen.add(prior.id);cursor=prior;}}
  for(const project of model.projects){const versions=model.hosted_config_versions.filter(x=>x.content.project_id===project.id).sort((a,b)=>a.content.revision-b.content.revision);versions.forEach((v,i)=>{assert.equal(v.content.organization_id,project.organization_id);assert.equal(v.content.revision,i+1);assert.equal(v.content.previous_version_id,i?versions[i-1].content.id:null);if(i)assert.ok(time(v.content.created_at)>time(versions[i-1].content.created_at));assert.equal(v.content_digest,digestContent(v.content));assert.ok(v.content.allowed_origins.every(o=>project.allowed_origins.includes(o)));assert.ok(time(v.content.created_at)<=time(v.lifecycle.updated_at));});}
  for(const org of model.organizations)if(org.state!=='active'){assert.ok(model.projects.filter(x=>x.organization_id===org.id).every(x=>x.state!=='active'));assert.ok(model.key_references.filter(x=>x.organization_id===org.id).every(x=>!['active','pending'].includes(x.state)));assert.ok(model.role_assignments.filter(x=>x.organization_id===org.id).every(x=>x.state!=='active'));}
  return true;
}

export function evaluateConfigActivation(model,command){
  try{structuralInput(model,command);coreInvariant(model);}catch{throw new Error(INVALID_INPUT);}
  const original=clone(model),next=clone(model),org=next.organizations.find(x=>x.id===command.organization_id),project=next.projects.find(x=>x.id===command.project_id),configs=by(next.hosted_config_versions,x=>x.content.id),target=configs.get(command.target_config_version_id),current=project&&configs.get(project.active_hosted_config_version_id);
  let reason=null;
  if(!org||!project||project.organization_id!==command.organization_id||!target||target.content.organization_id!==command.organization_id||target.content.project_id!==command.project_id)reason='binding_mismatch';
  else if(org.state!=='active'||project.state!=='active'||!current||current.content.organization_id!==command.organization_id||current.content.project_id!==command.project_id||current.lifecycle.state!=='active'||target.lifecycle.state!=='retired'||target.content.id===current.content.id||target.content.revision>=current.content.revision||!isAncestor(configs,current,target))reason='invalid_lifecycle';
  else if(project.active_hosted_config_version_id!==command.expected_active_config_version_id)reason='concurrent_state_mismatch';
  else if(!grantAt(next,command))reason='authorization_denied';
  const common={command_id:command.id,request_id:command.request_id,timestamp:command.timestamp};
  if(reason)return{state:original,result:{...common,outcome:'rejected',reason_code:reason,changed:false,active_config_version_id:project?.active_hosted_config_version_id??null},audit:auditFor(command,'rejected',reason)};
  const previous=current.content.id;project.active_hosted_config_version_id=target.content.id;project.updated_at=command.timestamp;current.lifecycle={state:'retired',updated_at:command.timestamp};target.lifecycle={state:'active',updated_at:command.timestamp};
  return{state:next,result:{...common,outcome:'accepted',reason_code:'activated_prior_content_version',changed:true,previous_active_config_version_id:previous,active_config_version_id:target.content.id},audit:auditFor(command,'accepted')};
}

export function invariant(model){
  try{structuralModel(model);coreInvariant(model);assert.equal(by(model.transition_scenarios).size,model.transition_scenarios.length);
  const commands=model.transition_scenarios.map(x=>x.command),results=model.transition_scenarios.map(x=>x.result),audits=model.transition_scenarios.map(x=>x.audit_event);assert.equal(by(commands).size,commands.length);assert.equal(by(commands,x=>x.request_id).size,commands.length);assert.equal(by(results,x=>x.command_id).size,results.length);assert.deepEqual(sorted(commands.map(x=>x.id)),sorted(results.map(x=>x.command_id)));assert.equal(by(audits).size,audits.length);assert.equal(by(audits,x=>x.command_id).size,audits.length);assert.equal(by(audits,x=>x.request_id).size,audits.length);
  const projects=by(model.projects),configs=by(model.hosted_config_versions,x=>x.content.id);
  for(const scenario of model.transition_scenarios){const {command,result,audit_event:a,before,expected_after}=scenario,project=projects.get(command.project_id),target=configs.get(command.target_config_version_id),current=configs.get(command.expected_active_config_version_id);assert.equal(project?.active_hosted_config_version_id,before.active_config_version_id);assert.equal(before.project_id,command.project_id);assert.equal(before.target_config_version_id,command.target_config_version_id);assert.equal(current?.lifecycle.state,before.active_config_state);assert.equal(target?.lifecycle.state,before.target_config_state);assert.equal(command.timestamp,model.effective_at);assert.equal(result.command_id,command.id);assert.equal(result.request_id,command.request_id);assert.equal(result.timestamp,command.timestamp);assert.equal(a.command_id,command.id);assert.equal(a.request_id,command.request_id);assert.equal(a.timestamp,command.timestamp);assert.equal(a.actor_principal_id,command.actor_principal_id);assert.equal(a.organization_id,command.organization_id);assert.equal(a.project_id,command.project_id);assert.equal(a.config_version_id,command.target_config_version_id);const evaluated=evaluateConfigActivation(model,command);assert.deepEqual(evaluated.result,result);assert.deepEqual(evaluated.audit,a);if(result.outcome==='accepted'){assert.notDeepEqual(evaluated.state,model);assert.deepEqual({project_id:command.project_id,active_config_version_id:evaluated.state.projects.find(x=>x.id===command.project_id).active_hosted_config_version_id,active_config_state:evaluated.state.hosted_config_versions.find(x=>x.content.id===command.target_config_version_id).lifecycle.state,prior_config_version_id:command.expected_active_config_version_id,prior_config_state:evaluated.state.hosted_config_versions.find(x=>x.content.id===command.expected_active_config_version_id).lifecycle.state,updated_at:command.timestamp},expected_after);assert.notEqual(result.previous_active_config_version_id,result.active_config_version_id);}else{assert.deepEqual(evaluated.state,model);assert.deepEqual(expected_after,{unchanged:true,project_id:before.project_id,active_config_version_id:before.active_config_version_id,active_config_state:before.active_config_state,target_config_version_id:before.target_config_version_id,target_config_state:before.target_config_state});}}
  return true;}catch{throw new Error(INVALID_INPUT);}
}
